### ISSUE TITLE
Investigate `vds_config.xml`

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#101]
In the PeMS Clearinghouse feed there is regularly updated file [`vds_config.xml`](https://pems.dot.ca.gov/feeds/vds_config.xml). It contains a snapshot of the VDS metadata for the present day. There are a few questions we have about this file:

1. Does it contain any information that is *not* in the `STATION_STATUS` or `STATION_META` files? @kengodleskidot indicated that he saw some information about the controller to station mapping, though I was unable to find that. @kengodleskidot do you have any more information there?
2. If there is information that is not in the above tables, how would we want to ingest and parse it?

**Comment by kengodleskidot** [comment]
The [vds_config.xml](https://pems.dot.ca.gov/feeds/vds_config.xml) file contains the following data and associated relationships that we will need to capture for table, reporting and visualization development:

- Which counties and cities are associated with a specific district with identifying ID's
- Freeway crossings located along routes for each district

State, City, County and District data are contained in tables that @pingpingxiu-DOT-ca-gov is migrating over in the CITIES, COUNTIES, DISTRICTS, STATES tables. The freeway crossings are located in the FWY_CROSSINGS table that is also being migrated over. I was mistaken about the controller to station association as this is located in each district configuration file, not the vds_config.xml. Apologies for any confusion.

**Comment by ian-r-rose** [comment]
> Which counties and cities are associated with a specific district with identifying ID's

Correct me if I'm wrong, but I think counties, cities, and district are already in the `STATION_META` table. I'm unsure about the freeway crossing information. Is this inferrable from the state_pm and abs_pm data?

**Comment by kengodleskidot** [comment]
You are correct that cities, counties and districts are in the metadata by VDS (station). Unfortunately, the freeway crossing information is not, particularly the crossing information in District 1, 2 and 9 where we are getting no VDS data. 
PeMS generates reports at three geographical levels: the individual detector level (at a point along a freeway corridor), the spatial level (a freeway segment), and the geographical aggregate level (multiple freeways within a larger geographical area, such as a city, county, Caltrans District, or all of California). Do you think we can accomplish this using the STATION_META table only or would seed files/tables be beneficial for geographical aggregations?

**Comment by ian-r-rose** [comment]
Are crossing information available in the XML district configuration files that you've seen? Basically, I'm trying to understand whether we need to ingest `vds_config.xml`, or whether we can grab the same data from earlier in the process.

>  Do you think we can accomplish this using the STATION_META table only or would seed files/tables be beneficial for geographical aggregations?

I think we can at least do it at the city, county, district, freeway, or state level. The one that I don't see a way to do right now is freeway *segment*, which doesn't seem to be in any of the metadata files I've seen (including `vds_config.xml`). For freeway segments, we may need to bring in seed files, unless that's also available in the XML configuration files from the districts.

**Comment by ian-r-rose** [comment]
Thanks for the discussion @kengodleskidot! I'll go ahead and close this, but if we decide that we do need something from the `vds_config.xml` file, we can always reopen.
