### ISSUE TITLE
Add new Caltrans team member, Khoi Tran, to meetings, platforms, docs, etc.

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#104]
**Khoi Tran's email and GitHub username:**
- khoi.tran@dot.ca.gov
- khoitran510

**Things to add Khoi to...**
- [x] GitHub @britt-allen via ITOps – [ticket link](https://airtable.com/app1Jm2SLJEU3ljBr/pagUUMkYMw6S6Gg5n?BPJfY=sfsqQddx4Rwz7PzCR&detail=eyJwYWdlSWQiOiJwYWdRM3BIZWQ4eXdYd2VNRiIsInJvd0lkIjoicmVjUXVMSElUbEw5WHJMVmciLCJzaG93Q29tbWVudHMiOmZhbHNlfQ)
- [x] Meetings @jkarpen  
- [x] Google docs (if any) @jkarpen 

**Background on Khoi**
- Role: Transportation Engineer with a data focus
- Manager is Huang-Le C, and he wants him to learn Tableau, GIS, and Python (first two are likely out of scope)
- Khoi is replacing Christian Clarion
- Khoi is with Zhenyu's group for about 6 months and started 3 weeks ago
- Has experience working with DGS as a student assistant otherwise this is his first real job!

**Comment by britt-allen** [comment]
cc: @jasonlally and @ian-r-rose for awareness

**Comment by jasonlally** [comment]
Thank you @britt-allen

**Comment by britt-allen** [comment]
@jkarpen are you able to add khoi.tran@dot.ca.gov to our caltrans meetings, please?

**Comment by jkarpen** [comment]
@britt-allen I have added Khoi to tomorrow's dbt incremental models training as well as the weekly Caltrans Sprint Planning call. Is Khoi going to be involved in the data relay sever work with Pingping? If so I can add them to the weekly call with Ian and Pingping as well.

**Comment by britt-allen** [comment]
Thank you Josh! I am not sure, probably best to bring up Khoi's addition to the team with Zhenyu to get more clarity from him. @jkarpen

**Comment by kengodleskidot** [comment]
I just spoke with Zhenyu and Khoi's assistance will primarily be with the project management/administration side of things. We can include him in the future sprint meetings, but the technical aspects (dbt and Snowflake) will stay with Pingping, Zhenyu, and I for the time being.

**Comment by britt-allen** [comment]
Oh so interesting, that is different from what I heard from Ken and Khoi so I hope they get some internal alignment too!

**Comment by britt-allen** [comment]
I am going to hold off adding him to dbt and Snowflake then

**Comment by britt-allen** [comment]
based on this feedback from @kengodleskidot should we add Khoi to GitHub or hold off? @jasonlally

**Comment by jasonlally** [comment]
@britt-allen - I think yes to github if Khoi will need / benefit from access to seeing the issues and sprint plan.

**Comment by britt-allen** [comment]
awesome, can you approve my request here then please:
https://airtable.com/app1Jm2SLJEU3ljBr/pagUUMkYMw6S6Gg5n?detail=eyJwYWdlSWQiOiJwYWdRM3BIZWQ4eXdYd2VNRiIsInJvd0lkIjoicmVjUXVMSElUbEw5WHJMVmciLCJzaG93Q29tbWVudHMiOnRydWV9&BPJfY=sfsqQddx4Rwz7PzCR
