### ISSUE TITLE
Load raw 30-second data from db96

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#114]
Now that we have decided that it is impractical/impossible to load raw XML files for 30 second data (cf. #74), we'll instead load the data from db96.

Some steps that need to be worked out:

- [ ] #105 
- [ ] Set up Snowpipe architecture for the data loaded by #105 

- [x] Making sure speed column is included in the schema
- [x] Configuring workers / troubleshooting why the upload is taking a long time
- [x] #149
- [x] #150
- [x] #151

**Comment by ian-r-rose** [comment]
@pingpingxiu-DOT-ca-gov the files you are uploading to S3 are now being loaded into `RAW_PRD.DB96.VDS30SEC`. Let's get #105 merged an call this issue done!

**Comment by junlee-analytica** [comment]
Pingping approved and merged the data.
