### ISSUE TITLE
Load VDS metadata from db96

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#115]
Now that we are no longer trying to load the raw configuration files (cf #75 ) we are planning to get the data from db96->(actually, detector config log and other related meta table is in DWO.)

**Comment by ian-r-rose** [comment]
@pingpingxiu-DOT-ca-gov any updates here?

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Daily Update: 
I fixed the all NULL bug and there is additional problems with individual columns' type casting. 
Six table's dozens' of columns need to be proofread. 

@ian-r-rose @ZhenyuZhu-Caltrans @jkarpen @jasonlally

**Comment by ian-r-rose** [comment]
@pingpingxiu-DOT-ca-gov when you are satisfied with your scripts to load the metadata, can you start loading them to `RAW_PRD`?

**Comment by pingpingxiu-DOT-ca-gov** [comment]
I verified the data on RAW_DEV looks good. 

The sizes of the config tables are: 
11157, 58297, 61853, 5613692, 24448, 338813
for 

CONTROLLER_CONFIG, CONTROLLER_CONFIG_LOG, DETECTOR_CONFIG, DETECTOR_CONFIG_LOG, STATION_CONFIG, STATION_CONFIG_LOG

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Hi @ian-r-rose 

I need the right credentials, I currently hit below error: 
```
Executing command SNOWSQL_PWD="【REDACTED】" REQUESTS_CA_BUNDLE=/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt snowsql -a NGB13288 -u MWAA_SVC_USER_PRD -o insecure_mode=True -f /nfsdata/dataop/uploader/snowsql/snowsql_load_DETECTOR_CONFIG_LOG.sql -d RAW_PRD
250001 (08001): Failed to connect to DB: NGB13288.snowflakecomputing.com:443. Incorrect username or password was specified.
```

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Done, I have updated the script. I also uploaded the six configuration tables to Prod. Count verifications showed they are the same counts to the Dev environment. 
@ian-r-rose

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Summarizing today's conversation: 
* Six configuration tables has been verified by Ian on Snowflake
* Daily refresh will happen after backfilling. 

No outstanding works. I just need to update backfilling status, on a regular basis.  

@ian-r-rose @ZhenyuZhu-Caltrans

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Today status 20%: 
And it will take about 5 days or so to depletes the backlog queue. 
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/29831793-ab1e-433a-b989-1798d087cd04)

**Comment by jkarpen** [comment]
Closing as this has been completed, there will be a new issue created for follow-on work.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Today backfilling status: 

![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/f2ce3154-66a3-46ba-94f2-8c1c4f30a778)

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Today backfilling status: 50%
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/fda9e2f9-6cd5-4c4b-abd0-a51fc6e4a228)

**Comment by pingpingxiu-DOT-ca-gov** [comment]
@ZhenyuZhu-Caltrans @ian-r-rose

**Comment by pingpingxiu-DOT-ca-gov** [comment]
@ian-r-rose @ZhenyuZhu-Caltrans 
Backfill is as smooth as the curve. ETA for depleting queue and normal crawl is about 2 days, based on the 
markers on the curve

![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/b3662566-77be-4928-8dfb-ff2eb1b2074b)

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Today backfill almost completed. @ian-r-rose @ZhenyuZhu-Caltrans 
I will monitor closely as the automatic daily config refresh resume
 ![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/3d4436f3-a7d3-4574-ac65-cc727159c216)

**Comment by ian-r-rose** [comment]
@pingpingxiu-DOT-ca-gov any update here? I don't see any uploads of the daily config files today

**Comment by pingpingxiu-DOT-ca-gov** [comment]
@ian-r-rose @ZhenyuZhu-Caltrans 
Update: 

As of today morning around 9am, the backfill crawl completed. 
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/6e65a3c3-41f5-4a15-96fc-2c7618152a4f)

Next:

The daily cron for the config crawl happens at 19:00. 
So the latest config will be refresh in the night time of today.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
@ian-r-rose @ZhenyuZhu-Caltrans 

Relay back to normal. 
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/98f6fc49-4128-440b-841f-4a473f3721b6)

The six tables are all updated with the latest stamp: 
(1) CONTROLLER_CONFIG           2024-07-03 19:00:02     (it was on DEV, today's will be on PROD)
(2) CONTROLLER_CONFIG_LOG   2024-07-03 19:00:02      Succeeded
(3) DETECTOR_CONFIG                2024-07-03 19:00:02      Succeeded
(4) DETECTOR_CONFIG_LOG        2024-07-03 22:22:57    Succeeded (I did some played around at 22:22:57, after the 19:00:02 refresh)
(5) STATION_CONFIG                    2024-07-03 22:22:57    Succeeded (I did some played around at 22:22:57, after the 19:00:02 refresh)
(6) STATION_CONFIG_LOG            2024-07-03 19:00:02     Succeeded

**Comment by ian-r-rose** [comment]
Thanks for the update @pingpingxiu-DOT-ca-gov!
