### ISSUE TITLE
Aggregate raw 30-second data to five minutes

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#117]
Many downstream metrics (e.g., speed) are based on five-minute aggregations of the raw VDS data. Ideally, this would include imputations, but for the time being, we want to aggregate the un-imputed raw data to 5 minutes to unblock further metric development.

**Comment by AzamBeg-Caltrans** [comment]
30-sec flows should be _summed_ up over 5 mins, lets say into 'Lane_1_Flow_5m'.
30-sec occupancies should be _averaged_ over 5 mins, lets say into 'Lane_1_Occ_5m'.  
Then:
   Lane_1_Speed_5m = Lane_1_Flow_5m / Lane_1_Flow_5m / 600

**Comment by ian-r-rose** [comment]
@AzamBeg-Caltrans that's what is happening in this PR. I'm also averaging the speeds as reported by the clearinghouse data, but I don't know how reliable they are, so we should feel free to ignore them in favor of your computations

**Comment by kengodleskidot** [comment]
@ian-r-rose I will work on the speed calculation to recreate what I believe @AzamBeg-Caltrans is looking for. Do you want me to create a new branch to work on the speed calculation or should I make changes in the 5-minute-aggregates branch?

**Comment by ian-r-rose** [comment]
Let's do it in a new branch @kengodleskidot
