### ISSUE TITLE
Create zero-copy clones for CI and development of incremental models

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#120]
Now that we are starting to land some incremental models, we should rethink how our CI works. Right now, we are running a `dbt build` for every CI run. This won't work well for incremental models, since the dev schemas start empty, so we are effectively doing a full refresh for every test run. This is both slow and expensive!

dbt's best practices [recommend](https://docs.getdbt.com/best-practices/clone-incremental-models) doing a `dbt clone` before running CI so that incremental models get zero-copy clones to start with. This should significantly cut down on both time and expense.

Once we merge #118, we should set up zero copy cloning for incremental models (and possibly deferral for non incremental models).

**Comment by britt-allen** [comment]
Reference: [Clone incremental models as the first step of your CI job](https://docs.getdbt.com/best-practices/clone-incremental-models)

**Comment by britt-allen** [comment]
I believe this is done @ian-r-rose please refer to the screenshots. Lmk if i missed something.
<img width="1792" alt="Screenshot 2024-03-22 at 6 36 08 PM" src="https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/47340362/dc36aa09-408a-40cb-aeb5-629fc96d7f63">
<img width="1792" alt="Screenshot 2024-03-22 at 6 38 13 PM" src="https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/47340362/1dc94437-b07e-4042-89aa-1e6c48804571">

**Comment by ian-r-rose** [comment]
That looks correct to me! I think we'll just want to test it with a fake PR today to verify that it's working as intended

**Comment by ian-r-rose** [comment]
We may need to tweak a role permission or two to make deferral to production work well (this is what we had run into earlier during training).
