### ISSUE TITLE
Unpivot VDS data to long format

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#121]
The VDS data are currently stored in a "wide" format. This means that each lane is stored in its own column, i.e.

| ID | Date | Timestamp | flow_1 | flow_2 | ... | flow_8 | occ_1 | occ_2 | ... | occ_8 |
|---|------|------------|-------|--------|----|-----|--|--|--|--|
| | | | | | | | | | | |

This is typically considered worse for data analytics for a few reasons:

1. Relevant data is stored in the column name
2. It's more cumbersome to do aggregations (look at how many things are repeated for each lane in, e.g. #96 )
3. We carry around columns for station IDs that don't need them: most stations don't have eight lanes of detectors

I think it would be a good idea to standardize on "long" format:

| ID | Date | Timestamp | Lane | Flow | Occupancy |
|--|--|--|--|--| -- |

That is to say, we store the lane number in a column, and the metrics are not in repeated columns.

If we do this, it would also be a natural point to introduce detector IDs by matching on the lane number (which @kengodleskidot brought up in #95 )

**Comment by kengodleskidot** [comment]
@ian-r-rose I think this is a solid approach and see the advantages you listed above. Are you think all tables would be structured in "long" format or would we still retain some of the tables in "wide" format? Unpivoting the data from "wide" to "long" will impact how we incorporate legacy data as well as how our current external data customers get data which is based on the current "wide" data structure in the PeMS data warehouse.

**Comment by ian-r-rose** [comment]
I was thinking that most of the tables would be long, and that we would only pivot back to wide format for highly aggregated reports on an as-needed basis.

I can cook up some example tables to be a bit more concrete about it. One consequence of unpivoting to long is that your work in #96 (and all aggregate metrics at the detector level) would probably become simpler.
