### ISSUE TITLE
Figure out difference in station counts

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#122]
In #118  @kengodleskidot noticed that for a particular date there were different station counts between the PeMS data warehouse and the clearinghouse data we've been loading.

It's not clear what the source of this discrepancy is, but we should figure it out! Perhaps PeMS is keeping references to stations that were not active on the given date?

**Comment by kengodleskidot** [comment]
In our meeting on 3/29/24 I believe the station counts we are getting from the int_clearinghouse__station_meta model match very closely from the data were are seeing from the PeMS data warehouse. I will perform additional QA/QC on this topic this week and report my finding here.

**Comment by ian-r-rose** [comment]
Thanks for the update @kengodleskidot

**Comment by britt-allen** [comment]
"Based on using the valid_to and valid_from fields we are able to get close to good enough numbers for pems detector status and 5 minute summary" Ken

**Comment by ian-r-rose** [comment]
Woohoo!
