### ISSUE TITLE
Meta Issue - Performance Metrics

### ISSUE THREAD

**Issue by kengodleskidot** [cagov/caldata-mdsa-caltrans-pems#126]
Once the speed calculation is addressed (#125) we can begin to start calculating the various performance metrics in PeMS including but not limited to the following:

- [x] Vehicle Miles Travelled (#144)
- [x] #153
- [x] #152

These metrics lead into each other and should be handled together per Ken:
- [x] #155
- [x] #154
- [x] #156

A meeting has been established by @britt-allen on 3/28/24 to go over this topic so we can then break up the calculations amongst the staff. The discussion and formulas for these calculations can be found at https://pems.dot.ca.gov/?dnode=Help&content=help_calc and https://docs.google.com/spreadsheets/d/1TIOO70yCNvP-RHwW8W0uHBgUP4cEcDuU/edit?usp=sharing&ouid=117120674896343152721&rtpof=true&sd=true.

**Comment by britt-allen** [comment]
We need details for all the linked issues above to help with sprint planning and assigning

**Comment by junlee-analytica** [comment]
Ken has pushed to production and is reviewing the data with the team.

**Comment by junlee-analytica** [comment]
Productivity to be tracked separately with new issue.
