### ISSUE TITLE
develop training plan

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#13]

**Comment by jkarpen** [comment]
Assigning to myself for now to produce the first draft training plan, then will work with Britt to finalize.

**Comment by britt-allen** [comment]
I have already started work **[here](https://docs.google.com/document/d/1V8kJOVpsOfpRy_vkiCvPNAIYST0lNgsnfEFo7C_ZUb8/edit)** if useful, feel free to edit this

**Comment by jkarpen** [comment]
@britt-allen looks like I don't have access to the doc you linked above, I just sent an access request.

**Comment by jkarpen** [comment]
@melanie-logan @britt-allen 
Link to Training plan we looked at in our call today: https://docs.google.com/document/d/1V8kJOVpsOfpRy_vkiCvPNAIYST0lNgsnfEFo7C_ZUb8/edit?pli=1

**Comment by jkarpen** [comment]
Closing this as the training plan is completed and the team is now working on the necessary updates/changes.
