### ISSUE TITLE
Training Session: Advanced groupby/aggregation

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#136]
Focus of this would be how to use groupby and aggregation in the context of performance.

**Comment by britt-allen** [comment]
This looks fun! Would love to collab if it makes sense. :)

**Comment by britt-allen** [comment]
Can I be added to the training? @jkarpen

**Comment by jkarpen** [comment]
@britt-allen Sure thing, I just added you (4/11 at 2PM)

**Comment by britt-allen** [comment]
Reached out to Zhenyu today to schedule for early next week

**Comment by britt-allen** [comment]
[Slides](https://docs.google.com/presentation/d/1k-sX47xOckaKLVt5v-uFFd86Jpb9f_gaYPTJWoF6QQ8/edit?pli=1#slide=id.g2dee282c0d5_0_17) and [recording](https://innovation-ca.zoom.us/rec/component-page?action=viewdetailpage&sharelevel=meeting&useWhichPasswd=meeting&clusterId=us02&componentName=need-password&meetingId=UqkJYUDLV91LUvQOcV_TNQY2c9z4wz_w_4HPrP1tMITy9vwT5tGkC4UtRdQHpLfH.7ga3elHqagkwvbfM&originRequestUrl=https%3A%2F%2Finnovation-ca.zoom.us%2Frec%2Fshare%2Fx980vv_1wcq3IVHhjfWKVjbxX7xEjg8aZy-ZOBh4kHWrwvf8ZnSiWjI9IllYHZLR.Eq6-uv7YzOVoP_LW) - Passcode: LVq#zV9h

**Comment by britt-allen** [comment]
[Slides](https://docs.google.com/presentation/d/1k-sX47xOckaKLVt5v-uFFd86Jpb9f_gaYPTJWoF6QQ8/edit?pli=1#slide=id.g2dee282c0d5_0_17) and [recording](https://innovation-ca.zoom.us/rec/component-page?action=viewdetailpage&sharelevel=meeting&useWhichPasswd=meeting&clusterId=us02&componentName=need-password&meetingId=UqkJYUDLV91LUvQOcV_TNQY2c9z4wz_w_4HPrP1tMITy9vwT5tGkC4UtRdQHpLfH.7ga3elHqagkwvbfM&originRequestUrl=https%3A%2F%2Finnovation-ca.zoom.us%2Frec%2Fshare%2Fx980vv_1wcq3IVHhjfWKVjbxX7xEjg8aZy-ZOBh4kHWrwvf8ZnSiWjI9IllYHZLR.Eq6-uv7YzOVoP_LW) - Passcode: reach out to britt
