### ISSUE TITLE
Training session: handling merge conflicts

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#138]
Link to slides from Ian's session with CARB: https://docs.google.com/presentation/d/1fW4uIwry8y5XE7SArPWkyxU2V6tNucHGE1A2K9fqID0/edit#slide=id.gd01156d741_1_3

**Comment by jkarpen** [comment]
@jkarpen see if Caltrans can do this 4/25 or 4/26, otherwise the week after

**Comment by britt-allen** [comment]
prep is been done

**Comment by britt-allen** [comment]
Recording from the session: https://drive.google.com/file/d/1YWbz0Elzw3Vfa67bGNrj4ppsZklnfkeT/view
