### ISSUE TITLE
VMT performance metric pipeline dev

### ISSUE THREAD

**Issue by ZhenyuZhu-Caltrans** [cagov/caldata-mdsa-caltrans-pems#144]
develop logic for VMT performance metric using aggregated flow and station length meta data, using 5 min agg data.

For a given unit of time and a given section of the freeway, the sum of the miles of freeway driven by each vehicle. For a section of fixed length, say L, the number of freeway miles driven is simply the flow for a period of time multiplied by the length L.

**Comment by jkarpen** [comment]
Closing, fixed by https://github.com/cagov/caldata-mdsa-caltrans-pems/pull/164
