### ISSUE TITLE
Create lightweight architecture diagram

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#147]
The goal is to create a lightweight architecture diagram for Caltrans showing only the pieces that happen after data leaves their network.

Having something this week (by 4/5) is a nice to have, otherwise by end of next week (4/12) if OK.

**Comment by melanie-logan** [comment]
![CalTrans Arch Diagram](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/150380765/52f791a8-eb8b-4532-9dbe-f239398c4acc)

**Comment by jkarpen** [comment]
Thanks @melanie-logan . I am adding this to the Caltrans Fact Sheet doc. Closing this issue as completed.

**Comment by melanie-logan** [comment]
Link to this editable version is [HERE] (https://lucid.app/lucidchart/invitations/accept/inv_eed60222-c274-4c48-80bd-f2088afc5fbf)
