### ISSUE TITLE
Investigate service stoppages (4/5-4/9, then down again from 4/9-4/11, still not up)

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#149]
New monitoring / alerting has been in place to reduce the down time within 24 hours (or facing escalations).

Related issues https://github.com/cagov/caldata-mdsa-caltrans-pems/issues/151.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
New monitoring / alerting has been in place to reduce the down time within 24 hours (or facing escalations). 

Related issues #151.

**Comment by jkarpen** [comment]
Closing, completed by #151
