### ISSUE TITLE
Productivity

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#152]
Productivity is the number of lane-mile-hours on the freeway lost due to operating under congested conditions instead of under free-flow conditions. When the freeway is in congestion - which we take to be when the speed is below a certain, user-selectable, threshold - we find the ratio between the measured flow and the capacity for this location. This drop in capacity is due to the fact that the freeway is operating in congested conditions instead of in free-flow. We then multiply one minus this ratio by the length of the segment to determine the number of equivalent lane-miles-hours of freeway which this represents. 

For the capacity we look at the historical measured data for each location and determine the maximum observed 15-minute flow. We use the maximum of this value and 2076 v/l/h as the capacity at each location.

Productivity is computed at the 5-minute level for each loop detector location as well as the aggregated value across all lanes.

**Comment by kengodleskidot** [comment]
Based on additional review of this metric it appears the lost productivity calculation is based on length, measured (or imputed) flow and capacity. The speed is only used to determine if it is less than the threshold selected by the user (35, 40, 45, 50, 55, 60 mph). This results in the same Lost Productivity result regardless of speed as long as it is less than the threshold selected. For example, if a lane has vehicles travelling at a speed of 30 mph the Lost Productivity value for all threshold speeds would be the same. If vehicles in a lane are travelling 51 mph the Lost Productivity value would be 0 for threshold speeds of 35, 40, 45 and 50 but the Lost Productivity value for 55 and 60 would be the same. This would be a good topic to discuss with the technical committee to see if a newer metric might be more useful and determine the existing use cases for the current metric.

**Comment by junlee-analytica** [comment]
Ian mentioned a full refresh is needed on the data. Potential training for CalTrans staff to trigger the refresh.

**Comment by junlee-analytica** [comment]
Ian has ran the full refresh on 5/23.
