### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#154]
Q is the sum of the VMT in a spatial and temporal region divided by the sum of the VHT in the same region. For a single location its interpretation is the average speed. But this value can be computed across many different links.
Q is computed at the 5-minute level for each loop detector location as well as aggregated across all lanes. The measures Q and TTI are just ratios of the base performance measures of VMT and VHT.

**Comment by jkarpen** [comment]
Closing, fixed by #164
