### ISSUE TITLE
Vehicle Hours Travelled

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#155]
Vehicle Hours Travelled (VHT) is calculated in PeMS over a given unit of time and a given section of freeway. VHT is the amount of time spent by all of the vehicles on the freeway. For a section of freeway of length L, that has F cars on it, it's simply the amount of time that these cars spent on that link. Formally, VHT= F * L / speed.

We compute this performance metric at the 5-minute level for each loop detector location as well as the aggregate across all lanes in a given segment. The measure can be summed up across time and space. This makes it quite easy for us to aggregate these measures to larger geographical regions and longer temporal periods.

**Comment by jkarpen** [comment]
Closing, fixed by https://github.com/cagov/caldata-mdsa-caltrans-pems/pull/164
