### ISSUE TITLE
Travel Time Index

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#156]
In PeMS the Travel Time Index (TTI) is the ratio of the average travel time for all users across a region to the free-flow travel time. The free-flow travel time is taken to be the time to traverse the link when traveling at 60MPH. For loop-based performance measures, the TTI is simply the free-flow speed divided by the performance measure Q.
We compute this performance measure at the 5-minute level for each loop detector location and the aggregate value across all lanes.

The measures Q and TTI are just ratios of the base performance measures of VMT and VHT.

**Comment by jkarpen** [comment]
Closing, fixed by https://github.com/cagov/caldata-mdsa-caltrans-pems/pull/164
