### ISSUE TITLE
Incrementalize `int_pems__detector_status`

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#161]
Over in #146 I recommended to @kengodleskidot that we just materialize `detector_status` as a table and don't worry about incremental logic. After a few days of watching it run, I think I may have gotten it wrong. It's taking ~90 minutes on an XS warehouse in CI, which isn't a *huge* deal, but does slow down dev cycles.

I think it might be worth making it an incremental model after all, what do you think @kengodleskidot and @britt-allen?

**Comment by britt-allen** [comment]
I agree with you on this, Ian!

**Comment by kengodleskidot** [comment]
I agree as well.

**Comment by jkarpen** [comment]
Closed by #148
