### ISSUE TITLE
Rename `int_pems__` models

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#162]
A number of models have been made with the `int_pems__` prefix. I think it might be a good idea to make them a bit more specific, since effectively every model in this project is related to PeMS. Per the [best practice](https://docs.getdbt.com/best-practices/how-we-structure/3-intermediate#intermediate-files-and-folders) documentation in dbt, the prefix could be something like line of business. In our case, I'd interpret that as broad use cases like diagnostics, performance metrics, etc.

What if we instead called a bunch of them `int_diagnostics__` or similar?

**Comment by kengodleskidot** [comment]
Are you thinking the schema (or something similar) is what we will replace "pems" with in the SQL model name? I like the idea!

**Comment by ian-r-rose** [comment]
Yes, that's exactly what I was thinking

**Comment by britt-allen** [comment]
Agree, thank you Ian for writing this up and proposing.

**Comment by britt-allen** [comment]
Are we also thinking of changing the 
```
detector_health_diag:
        +schema: detector_health
```
to

```
diagnostics:
        +schema: diagnostics
```
and all corresponding models to `int_diagnostics__`? @ian-r-rose @kengodleskidot
