### ISSUE TITLE
Use `big` and `small` parameters in `get_snowflake_refresh_warehouse()`

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#163]
Over in the `get_snowflake_refresh_warehouse()`, I added parameters for "big" and "small" to customize what warehouse sizes to use when running incremental models incrementally or when running them with a full refresh.

But I forgot to actually use those parameters! We need to add them here:

https://github.com/cagov/caldata-mdsa-caltrans-pems/blob/eb4b661ad777feb5820bae2b925da1a0bb4882d2/transform/macros/get_snowflake_refresh_warehouse.sql#L8-L12

**Comment by kengodleskidot** [comment]
Closed with PR #197
