### ISSUE TITLE
Speed Calculation Update Discussion

### ISSUE THREAD

**Issue by kengodleskidot** [cagov/caldata-mdsa-caltrans-pems#165]
As we start to work on performance metrics and eventually move into reports/visualizations I would like to explore updating the speed calculation to minimize outliers in our data based on the simplified speed calculation we are currently using. I propose using the following update to the logic to determine speed:

If speed is being reported by a detector use the reported speed
If no speed is being reported then calculate speed using the simplified speed equation
     If a speed calculation using the simplified speed equation is over 90mph or null use a free flow speed of 65mph

I believe this change will give us speed and performance metrics more in line of what we would expect to see in the real world. I am open to the group's thoughts and inputs on this topic since it would involve recalculating the five-minute aggregate table.

**Comment by ian-r-rose** [comment]
This sounds like a reasonable plan @kengodleskidot. Based on your logic, I think we may want to make the 5-minute aggregate table compute *just* the average speed based on that reported by the detector. That would help keep this expensive-to-calculate model as simple and stable as possible. Then your follow-up logic could be done in downstream models. Does this work for you?

>  If a speed calculation using the simplified speed equation is over 90mph or null use a free flow speed of 65mph

I would probably prefer to have it as null rather than a made up number.

**Comment by ian-r-rose** [comment]
> @ian-r-rose since we are only getting speed values from a small group of detectors what model would be best to perform the simplified speed calculation if not the 5-min aggregate model?

We could put some of the more complex speed reasoning in your 5-minute performance metrics model. It's not the only choice, but shouldn't be too hard to add there

**Comment by kengodleskidot** [comment]
FYI @mmmiah is working on updating the associated speed models

**Comment by britt-allen** [comment]
> This sounds like a reasonable plan @kengodleskidot. Based on your logic, I think we may want to make the 5-minute aggregate table compute _just_ the average speed based on that reported by the detector. That would help keep this expensive-to-calculate model as simple and stable as possible. Then your follow-up logic could be done in downstream models. Does this work for you?
> 
> > If a speed calculation using the simplified speed equation is over 90mph or null use a free flow speed of 65mph
> 
> I would probably prefer to have it as null rather than a made up number.

I agree with Ken and agree with Ian's edit regarding preserving nulls rather than making up a number.
