### ISSUE TITLE
Data Relay Service Issue

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#168]
This is an alert with regarding to the yesterday service healthiness. Certain action needs to be taken. The owner of the service is Pingping Xiu and supervisor Zhenyu Zhu, in Traffic Operations @ Caltrans. This issue details is pending for triaging, and needs further clarification. This message is sent from a cron-automated script named etc launch_service_monitor_daily.sh on the svgcmdl02 linux machine in Caltrans internal network.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
@ian-r-rose this is sent from the test run.

**Comment by ian-r-rose** [comment]
Thanks @pingpingxiu-DOT-ca-gov, closing as this was a test!
