### ISSUE TITLE
Imputation: compute from global coefficients

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#170]
Perform imputation on the 5-minute unimputed data based on linear regression from all detectors in a district, as documented in the [User manual](https://pems.dot.ca.gov/Papers/PeMS_Intro_User_Guide_v6.pdf).

There is also an opportunity to refine what is considered "global". What's described in the user manual is using all detectors in a district, but we could also do, e.g., all detectors in a district on the same freeway, or all detectors within a certain distance of the one in question.

<img width="772" alt="image" src="https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/5728311/deeba248-ad2c-4ead-80a2-bb60c1f4c8b7">

The algorithm is described in more detail [here](https://pems.dot.ca.gov/Papers/loops_asv2.pdf).

Additional Information: Linear regression from neighbors based on global coefficients. This imputation method is a method similar to compute from local coefficients. The only caveat is that there are some loops which never report data. In that situation it is not possible to compute local regression coefficients. Therefore, we compute global regression coefficients. These coefficients represent the general relationship seen throughout the route.

**Comment by mmmiah** [comment]
We are working on this and have opened new issues #199

**Comment by britt-allen** [comment]
Why is this issue closed? You linked to a pull request, not a new issue @mmmiah . I don't understand how pull request 199 relates to this issue. This issue can't be closed unless a PR closes it out or we decide as a team this is unplanned work.

**Comment by mmmiah** [comment]
@britt-allen , alright, the pull #199 aims to fulfill the goal mentioned in this issue, but the PR #199 is in initial stage. I thought/misunderstand that you want me to close #170 based on your comments. I have edited the final goal of #199 as 'This code identified all the upstream and downstream stations within five miles buffer that is within same district, route, directions and highways. The goal of this model is to identify the stations that can be used to develop linear regression model and determine the global coefficient to impute the missing performance metrics where local regression models fails.'

**Comment by junlee-analytica** [comment]
Global coefficients changed to regional coefficients.

**Comment by britt-allen** [comment]
Is this issue still being worked on?

**Comment by ian-r-rose** [comment]
Yes, in #250
