### ISSUE TITLE
Imputation: temporal medians

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#171]
As described in the PeMS user guide:

<img width="772" alt="image" src="https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/5728311/afdd3bbd-e820-4f19-b4e3-4996a8e95fcf">

It's a little vague, but seems like it could be reasonably straightforward? Lots of use of medians :/

Additional details:
Temporal medians - The local and global linear regression models can break down when adjacent detectors don't report data themselves, in which case a temporal median may be used. A temporal median is a value that is the median at a particular location for a particular day of the week and time of day over the last N weeks. For example, if you discover that you have a hole at 3pm on Wednesday at a particular loop then you can look back over the past N Wednesdays at 3pm for this loop and take the median of those measurements and use that here. The values to be used in the medians should be from actual observed values and not imputed. If normalized values are to be used, we would want to make sure that a minimum number of samples were recived. For example, the values to be used would need to have 8 or more samples in the same 5-minute timeframe.

**Comment by britt-allen** [comment]
This imputation process may be weaker than our other methods, like regression. We are holding off on this based on our discussion at our 5/16 weekly sprint call

**Comment by britt-allen** [comment]
Still need to understand what this means as well

**Comment by mmmiah** [comment]
@britt-allen @ian-r-rose  It might follow below steps-
1. Calculate speed, volume and occupancy for each five minutes in each day of weeks for a year or for historical years of time
2. take the median five mins speed, volume, and occupancy for each five minutes in seven days of a week (Monday to Saturday), you will get 12 (12 value in each hour) X 24 hours in a day X 7 days a week=2016 median value of each parameter. Use these value directly to replace any corresponding missing value. 

However, it is better if we get some official documents that describes details!. @kengodleskidot , do we have details description of this method?

**Comment by jkarpen** [comment]
@ian-r-rose will create separate issue for next steps and close this one out.

**Comment by ian-r-rose** [comment]
We've decided not to do this one, and instead will work on a rough replacement in #272
