### ISSUE TITLE
Use device-reported speed in 5-minute aggregation

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#174]
Per the discussion in #165, we'd like to use the device-reported speed in the 5-minute unimputed aggregations. Downstream models may choose different methods for computing speed, but we're keeping the 5-minute model as simple as possible.

**Comment by kengodleskidot** [comment]
FYI @mmmiah is working on this model update

**Comment by ian-r-rose** [comment]
Great, thanks @mmmiah!

**Comment by kengodleskidot** [comment]
Closed with PR #196
