### ISSUE TITLE
Relay Server - Monitor malfunction

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#175]
There is a bug identified by the newly setup dashboard: 

![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/9e0891cb-2a6d-4d88-8a14-64e79df71049)

D3 behaves different from other districts. 

Need further troubleshooting. 
@ian-r-rose 
@ZhenyuZhu-Caltrans

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Root cause identified: 
It was due to the monitoring script not able to handle the irrelevant Kafka consumer topic information. 
In `D3`, the corresponding consumer for uploading the D3 data to AWS has a noise subscription (D3 subscribing to D11), which caused inaccurate monitoring results. It might have introduced by manual operation errors in the past. 

![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/cecca5f2-081b-4c22-8419-ec350f81941e)

And the changes was applied on the Relay Server `D2`'s `/etc/check_topic_lag.sh` script, adding below filter to excluding that noise configuration. (I wasn't able to delete that entry directly on the Kafka server, so I have to do the removal in the monitoring script. )
```
... | grep -v "D3.*D11" |
```

After applying that filter,  the dashboard is recovered. 
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/db45db51-15c1-4fb4-9f84-fbcd4876e476)


Key Learnings: 
* Need to use one consumer group for all topics, rather than each consumer group for one topic, because Kafka seems to have a lot inconvenience on managing multi-consumer-group status. 

TODO: (I'll accumulate TODO-s into a new issue called "Relay Server Trust Work Items". 
* need to centralize the service monitoring scripts 
* need to use a single consumer group for all the topics in AWS uploader stage.

**Comment by ian-r-rose** [comment]
Thanks for this update @pingpingxiu-DOT-ca-gov !
