### ISSUE TITLE
Relay Server - When data cross midnight, only one day's data sent to AWS

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#176]
@ian-r-rose 
@ZhenyuZhu-Caltrans

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Added new logs for monitoring the parquet format.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
The log is showing the relay server handles the cross midnight situation right.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Root cause of this bug: 
   the uploading snippet was placed outside the loop so only one entry from the list was uploaded, instead of the full entries in the list. 

@ian-r-rose @ZhenyuZhu-Caltrans 

Solved the bug. The current Relay should not drop data from today on.

**Comment by ian-r-rose** [comment]
Nice!
