### ISSUE TITLE
Relay Server - Trust Items

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#177]
- [x] Moved the local kibana to D2 linux server.
- [ ] Need to renew the github token for alert
- [ ] need to centralize the service monitoring scripts
- [ ] need to use a single consumer group for all the topics in AWS uploader stage.
- [ ] need to document the process on how to do schema normalization to the data. 
- [x] Add count dashboard for monitoring

Relate Issues: #149 #151

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Today, 
Moved the local kibana to D2 linux server.

**Comment by jkarpen** [comment]
@pingpingxiu-DOT-ca-gov Since this is a "large" sized issue, could you break this up into smaller issues (Medium or smaller)?

**Comment by jkarpen** [comment]
Per @pingpingxiu-DOT-ca-gov this issue is no longer needed. The unchecked boxes in the description are no longer necessary to complete.
