### ISSUE TITLE
Relay Server - Interference from ad-hoc troubleshooting to main workflow

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#178]
Currently, the --window parameter to the `table_aws_uploader.py` controls how much data it upload to AWS in one batch. 
Default is `3600`. 
After I use --window equals 1 for testing, and changing back to `3600`, the script still behaves like --window equals 1.

**Comment by ian-r-rose** [comment]
Closing as resolved
