### ISSUE TITLE
Infrastructure Incident that impacts Relay

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#179]
Our DMZ server (svgcmdl01) is down and with all its services (including the Relay Job OraclePuller) 

I will monitor its status and check whether the auto-rebooting script works when the server go back up. 

From: Pingping.Xiu@dot.ca.gov <s159123@svgcmdl02.dot.ca.gov> 
Sent: Friday, April 19, 2024 3:03 PM
To: Xiu, Pingping@DOT <Pingping.Xiu@dot.ca.gov>
Subject: Relay_Status_UNHEALTHY

Service Status Report
-- Background info --
* The purpose of this report is to monitor the Data Relay server for PEMS modernization project
* This report was run at the time Fri Apr 19 150001 PDT 2024
* The report is generated from svgcmdl02 machine on etc launch_service_monitor.sh
* The owner is [pingping.xiu@DOT.ca.gov](mailto:pingping.xiu@DOT.ca.gov) at BIA team in Traffic Operation, Caltrans

-- Streaming / Registry Service Status -- Core Service running at svgcmdl03 2181 is healthy.
Core Service running at svgcmdl03 9092 is healthy.
Core Service running at svgcmdl04 2181 is healthy.
Core Service running at svgcmdl04 9092 is healthy.
Core Service running at svgcmdl05 2181 is healthy.
Core Service running at svgcmdl05 9092 is healthy.
Core Service running at svgcmdl02 9200 is healthy.
Core Service running at svgcmdl04 8092 is healthy.

-- Runner Status --
* ORACLE_PULLER running on svgcmdl01 is UNHEALTHY
* TASK_GENERATOR running on svgcmdl02 (under s159123) is healthy
* AWS_UPLOADER running on svgcmdl02 (under s159123) is healthy

-- Topic Lags --
puller_D4.VDS30SEC,301227773,304074390,2846617
puller_D7.VDS30SEC,384297116,387764331,3467215
puller_D11.VDS30SEC,65865626,66461051,595425
puller_run_004,53271,54282,1011
puller_D5.VDS30SEC,44028992,44435456,406464
puller_D3.VDS30SEC,134499251,135702157,1202906
puller_D12.VDS30SEC,129555155,130595105,1039950
puller_D8.VDS30SEC,112314719,113323078,1008359
puller_D6.VDS30SEC,47393420,47827327,433907
puller_D10.VDS30SEC,87357550,88156192,798642
---------------Sort---------------
The total lag: 23600992
LAG_STATUS: healthy

-- Overall Relay Service Status --
Relay Status UNHEALTHY at Fri Apr 19 15:03:08 PDT 2024 The information will be put into the file /var/log/relay_monitor/20240419.txt
Please do not forget to remove the UNHEALTHY string from that file /var/log/relay_monitor/20240419.txt after mitigation. Otherwise, alert will be created tomorrow.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
The downtime ends. 
The service's OraclePuller got back to normal by itself, with the auto rebooting.

**Comment by ian-r-rose** [comment]
Thanks for the update @pingpingxiu-DOT-ca-gov!
