### ISSUE TITLE
Introduce `pems_clearinghouse_start_date` variable

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#181]
As we are in the thick of defining some of our base, large models, we are recomputing some quite large tables with some regularity. This is both expensive and time consuming.

What do we think about introducing a new variable `pems_clearinghouse_start_date` which can be set to, e.g., 2023-01-01 for the time being? We can filter our base models according to this date, and once the dust settles a bit, move it back to the actual start of the historical PeMS data.

**Comment by kengodleskidot** [comment]
@ian-r-rose I agree with your approach and like the idea. The proposed start date should be fine for where we are at in the project and it gives us a full year of data which I believe is adequate for the time being to perform QA/QC. There may be other anomalies farther back in time but these will be easier to identify once we have some visualization and reporting tools.

**Comment by ian-r-rose** [comment]
@kengodleskidot would you be willing to take this on?
