### ISSUE TITLE
AADT (Average Annual Daily Traffic)

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#185]
## Computation of AADT for ITS Stations
Another quantity that we precompute offline from traffic flow data is the AADT, or **Average Annual Daily Traffic**. Conceptually, this is simply the total vehicle flow per day, averaged over a year-long period. We compute the AADT in 8 different ways, for every ITS station in the system and for every 12-month period which starts at the first of a calendar month. This section describes the various algorithms used to compute these quantities.

Conventional methods for calculating AADT values require that the input data meet certain completeness standards. For example, the AASHTO's 1992 "Guidelines for Traffic Data Programs" requires that a full day's worth of flow data be available for every day of the week and for every month of the year, with no imputed data allowed. However, much real-world sensor data does not meet such rigorous standards. Several research groups have developed variant procedures designed to accomodate typical patterns of missing data and minimize their distorting effect on the averages. PeMS computes AADT values using 8 of these methods, which are summarized below. More details can be found in the paper "Using Incomplete Archived ITS Data to Calculate Annual Average Traffic Statistics" by Shawn Turner and Eun Sung Park (Proceedings of the Transportation Research Board 87th Annual Meeting, Washington, D.C., 2008). The inputs to these methods are **the total station flow values (across all lanes) aggregated to the hourly or daily level, depending on the algorithm**. In every case, **no imputed data is allowed**; only those hours or days for which all data points are real observed values are included in the computations.

The 8 methods used to calculate AADT in PeMS, for each station and each 12-month period, are as follows:
| AADT Method  | Description                                  |
|--------------|----------------------------------------------|
| AADT_1       | Arithmetic Mean                              |
| AADT_2       | ASTM Standard 1442                           |
| AADT_3       | Conventional AASHTO Procedures               |
| AADT_4       | Provisional AASHTO Procedures                 |
| AADT_5       | Sum of 24 Annual Average Hourly Traffic Volumes |
| AADT_6       | Modified ASTM Standard                       |
| AADT_7       | Modified Conventional AASHTO                 |
| AADT_8       | Modified Provisional AASHTO                  |

* AADT_1: Arithmetic Mean
This is simply the average of all daily traffic flows over the entire year.
* AADT_2: ASTM Standard 1442
This procedure begins by calculating Monthly Average Days of the Week (MADW) values, which are the average daily flows for each day of the week and each month of the year (a total of 84 values). From these, 12 Monthly Average Daily Traffic (MADT) values are calculated as the average of the non-missing MADW values for each month. Finally, AADT_2 is computed as the average of all MADT values. This algorithm allows one or more of the 7 weekday values to be missing for the MADT computation, but none of the 12 MADT values may be missing for the final average.
* AADT_3: Conventional AASHTO Procedures
This algorithm also starts with the MADW values, computed as described above for AADT_2. From these, an Annual Average Days of the Week (AADW) value is computed for each day of the week as the average across all 12 months. Finally, AADT_3 is computed as the average of these 7 AADW values.
* AADT_4: Provisional AASHTO Procedures
This procedure first calculates, across all 12 months, the monthly average flow for each hour of the week (MAHW), which results in 24 x 7 = 168 values per month. Then for each month and day of the week, the 24 MAHW values are summed to produce a MADW value. Then, just as in AADT_3, 7 AADW values are produced as the averages of MADW across 12 months, which are then averaged to yield AADT_4.
* AADT_5: Sum of 24 Annual Average Hourly Traffic Volumes
For each hour of the day, hourly traffic flow is averaged across all days of the year, resulting in 24 annual average hourly values. AADT_5 is computed as the sum of the 24 hourly values.
* AADT_6: Modified ASTM Standard
This procedure is a modified version of AADT_2, in which 1 of the 12 MADT values may be missing for the final AADT calculation.
* AADT_7: Modified Conventional AASHTO
This procedure is a modified version of AADT_3, in which 1 of the 12 MADW values may be missing in the AADW subcomputation, and/or 1 of the 7 AADW values may be missing in the final AADT_7 computation.
* AADT_8: Modified Provisional AASHTO
Similarly, this procedure is a modified version of AADT_4, in which 1 of the 12 MADW values may be missing in the AADW subcomputation, and/or 1 of the 7 AADW values may be missing in the final AADT_8 computation.

Lastly, PeMS also computes `k-factor`
* k-factor
Along with the 8 AADT values, PeMS computes a "k-factor" for each station and for each month. This is defined to be **the 30th highest hourly traffic flow observed at that station among all hours of the preceding year**.

Here is the paper referenced above: 
[turner-park-2008-incomplete-archived-data-of-intelligent-transportation-systems-for-calculation-of-annual-average.pdf](https://github.com/user-attachments/files/16091114/turner-park-2008-incomplete-archived-data-of-intelligent-transportation-systems-for-calculation-of-annual-average.pdf)

**Comment by pingpingxiu-DOT-ca-gov** [comment]
@kengodleskidot 
@ian-r-rose 
@ZhenyuZhu-Caltrans 

I decided to take this as next for data modeling because it is tightly related to the relay
completeness (i.e. Annual metrics)

Let me know any questions.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
> We compute the AADT in 8 different ways, for every ITS station in the system and for every 12-month period which starts at the first of a calendar _month_. 

Should it be a _year_ or _month_ ? 
@kengodleskidot

**Comment by junlee-analytica** [comment]
This issue will be moved over as a sprint goal in Sprint 2024-11.

**Comment by mmmiah** [comment]
I think that k-factors need to be handled in different model as it is monthly value while AADT is the annual value!

**Comment by mmmiah** [comment]
Created the PR and ready for review of this task!
