### ISSUE TITLE
Bottleneck Duration

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#186]
Bottleneck Identification Algorithm
The PeMS system runs a bottleneck identification algorithm every day. The original algorithm was presented in, "Systematic Identification of Freeway Bottlenecks," by Chen, C., Skabardonis, A., Varaiya, P. (2003). Transportation Research Board, 2004.

This algorithm attempts to identify bottlenecks on the freeway system at every detector. At a high level, a bottleneck exists at a particular detector when there is a persistent drop in speed from the current detector to the detector immediately upstream. Specifically we have the following defining conditions:

There is a drop in speed of at least 20 mph.
The speed at the current detector is less than 40 mph.
The detectors are less than 3 miles apart.
The speed drop persists for at least 5 out of any 7 contiguous 5-minute data points.
When localizing PeMS to metric units these thresholds are translated directly.
If all of these conditions are met then we declare that there is a bottleneck at this location that has been activated for all of the 7 5-minute time points (technically the bottleneck is between these two detectors - we don't know where exactly. We declare that the bottleneck is at the detector where the speed has dropped.) We perform this analysis for each of three time periods: AM shift (5am-10am), noon shift (10am-3pm), and PM shift (3pm-8pm). For each location where a bottleneck is activated we compute the following:

**Bottleneck Duration**: This is how long the bottleneck was active during that particular shift on that day.

**Comment by britt-allen** [comment]
AM off peak (or day off peak??), AM peak (or Day peak??), PM peak, PM off peak, holiday - these are additional time frames we might need to consider? Can you clarify and expand on what you mentioned this morning @kengodleskidot 

We discussed potentially creating a table to capture this.

**Comment by britt-allen** [comment]
Right now, the three time periods listed above are not something we need to worry about as identified in this morning's discussion. We'll re-visit this at a later time.

**Comment by britt-allen** [comment]
Based on the technical discussion yesterday do we want to continue using delay_60_mph or switch to delay_65_mph? @kengodleskidot

**Comment by britt-allen** [comment]
Here's the outline I've been using to keep me grounded in this work: https://docs.google.com/spreadsheets/d/1gv4S8BsSt4gScx8kHNzhGjSH-z4srUGEiehqmLdvfdg/edit#gid=0

**Comment by kengodleskidot** [comment]
> Based on the technical discussion yesterday do we want to continue using delay_60_mph or switch to delay_65_mph? @kengodleskidot

Continue using delay_60_mph.

**Comment by kengodleskidot** [comment]
Attached is the paper identified in the initial comment above: 
[Systematic_Identification_of_Freeway_Bottlenecks (1).pdf](https://github.com/user-attachments/files/15594486/Systematic_Identification_of_Freeway_Bottlenecks.1.pdf)

**Comment by kengodleskidot** [comment]
GIS representation of bottleneck: https://gisdata-caltrans.opendata.arcgis.com/maps/9509bf8a475f49b4a9c79bac15f8b479

**Comment by kengodleskidot** [comment]
> AM off peak (or day off peak??), AM peak (or Day peak??), PM peak, PM off peak, holiday - these are additional time frames we might need to consider? Can you clarify and expand on what you mentioned this morning @kengodleskidot
> 
> We discussed potentially creating a table to capture this. This may also be captured in a new issue.

I just wanted to close the loop on this and mention that we added variables for the on-peak/off-peak timeframes in #227. There is some additional work to be done on holiday's, but we will continue that discussion in #223.

**Comment by kengodleskidot** [comment]
FYI additional information about bottlenecks from FHWA for reference. These will not impact our current analysis but could be useful in future discussions https://ops.fhwa.dot.gov/bn/lbr.htm and https://ops.fhwa.dot.gov/bn/bnchart.htm
