### ISSUE TITLE
Relay Server Minor Issue (Cron job may occasionally skip)

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#193]
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/82bbf55c-bcaf-47ca-a0b2-8bbba669e813)

Over the weekend, the monitor identified one situation the AWS_UPLOADER cron job skipped once. 
By design, it is auto-recoverable: the next cron job will first take care the previous one's workload and then the current. 

Still, worth verifying: 
- [ ] The Data is intact
- [ ] The cron job skipping is just one off (not due to some systemic issue. )

[Reproduceable Dashboard](http://svgcmdl02:5601/app/dashboards#/view/4438c280-fcfd-11ee-99ff-69aa747c5773?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-26T06:03:03.606Z',to:'2024-04-29T17:13:27.948Z'))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:'Consumer%20Lag',viewMode:view))

**Comment by pingpingxiu-DOT-ca-gov** [comment]
FYI @ian-r-rose @ZhenyuZhu-Caltrans

**Comment by britt-allen** [comment]
Can this issue be closed or moved to a sprint?

**Comment by ian-r-rose** [comment]
Closing as resolved, thanks @pingpingxiu-DOT-ca-gov
