### ISSUE TITLE
Relay Server (Adding six tables related to metadata)

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#195]
## Scope of Work
Relay the following tables:

CONTROLLER_CONFIG, CONTROLLER_CONFIG_LOG, DETECTOR_CONFIG, DETECTOR_CONFIG_LOG, STATION_CONFIG, and STATION_CONFIG_LOG6

## History
Original attempt of treating the tables as one shot (using `SELECT *`) failed, leading to a P0 bug https://github.com/cagov/caldata-mdsa-caltrans-pems/issues/202

**Comment by junlee-analytica** [comment]
Pingping is working with Ian to onboard a new table into Snowflake. Connecting to Snowflake issue has been resolved.

**Comment by ian-r-rose** [comment]
Closing as a duplicate of #115
