### ISSUE TITLE
Aggregating Delay at a Station

### ISSUE THREAD

**Issue by kengodleskidot** [cagov/caldata-mdsa-caltrans-pems#201]
We have recently updated the five-minute performance metric model with the delay metric per lane. In the PeMS User Guide it appears that the delay value aggregated across all lanes at a given station is not the sum of the per lane delay but instead it is calculated per the description below: 

- PeMS does not sum the per-lane delay to compute the aggregate delay for a VDS location. Rather, the system uses the aggregate speed (which is the flow-weighted speed across the lanes) and the aggregate flow as the inputs to calculate delay for a VDS location over a 5-minute period. This delay is used in all subsequent delay calculations in PeMS. For example, the hourly delay for a station equals the sum of twelve 5-minute delay calculations. Due to these complexities, PeMS neither computes the hourly delay per lane nor does it show the hourly delay per lane on the Time Series plots. This is to avoid confusion, because the sum of the hourly delay in each lane would not equal the hourly delay for the VDS.

When we look at aggregating the lane data to the station level for delay we will want to take this into consideration.

**Comment by ian-r-rose** [comment]
Thanks for flagging this @kengodleskidot!

**Comment by britt-allen** [comment]
Was this closed by #215?

**Comment by mmmiah** [comment]
@britt-allen , Yes, you can close it as we completed this task in #215
