### ISSUE TITLE
Relay Server Bug (P0) - Stuck due to new feature's bug

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#202]
## Background

Right now a task crawling the CONTROLLER_CONFIG_LOG table get crashed, 
and it does not clear the queue, so that all the normal operation get stalled. 

Working on that right now to get the faulty message out of the queue and 
develop mechanism to handle the CONTROLLER_CONFIG_LOG's specific failure. 

[Kibana dashboard](http://svgcmdl02:5601/app/dashboards#/view/4438c280-fcfd-11ee-99ff-69aa747c5773?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15d,to:now))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'Crawling%20Operation',viewMode:view))

## Solution
To remove the faulty message from the crawling queue, we have to perform the following sequence of the operations:

1. Retrieve the current consumer offset for the crawling queue topic. 
Log in to machine `svgcmdl02` and do
```
kafka-console-consumer.sh --bootstrap-server svgcmdl03:9092 --from-beginning --topic oracle_crawl_queue_topic --max-messages 1  --property print.offset=true
```
And get the offset from the output. Use `84336` for example

2. To get the delete-until offset, add `1` to the current consumer offset. (In this case, `84337`).

3. To perform the delete-until-offset operation, using the following command: 
```shell
echo '{"partitions":[{"topic":"oracle_crawl_queue_topic","partition":0,"offset":DELETE_UNTIL_OFFSET}],"version":1}' > /tmp/data.json; kafka-delete-records.sh $KR --offset-json-file /tmp/data.json
```
In which, the delete-until offset `DELETE_UNTIL_OFFSET` will be replaced by `84337`. 

4. Conduct the step 1 again to verify that the consumer's current message is changed.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
@ZhenyuZhu-Caltrans @ian-r-rose @britt-allen

**Comment by britt-allen** [comment]
Thank you Zhenyu for flagging and working on this! Can you link the pull request that will close this, please?

**Comment by pingpingxiu-DOT-ca-gov** [comment]
The related PR is https://github.com/cagov/caldata-mdsa-caltrans-pems/pull/105

**Comment by britt-allen** [comment]
Thanks for the update Zhenyu. I see the related PR is still open. Are you blocked on that?

**Comment by pingpingxiu-DOT-ca-gov** [comment]
It is done in terms of work, but I don’t know how to disable the “prettier” and “ruff”
To let pre-commit pass.

Yes, I’m blocked on those.
