### ISSUE TITLE
Possibly cluster base tables by district

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#207]
@pingpingxiu-DOT-ca-gov pointed out that it may be worth the additional clustering overhead to cluster our base tables by `district` (they are mostly clustered by just `sample_date` right now). I'm not 100% certain that it is useful, since data are already loaded by district, and micropartitioning might be effectively doing it already. But it's worth checking.

**Comment by jkarpen** [comment]
Backlogging this as it is now lower priority compared to the other optimization issues ongoing.

**Comment by jkarpen** [comment]
Per @pingpingxiu-DOT-ca-gov this issue is no longer needed.
