### ISSUE TITLE
Monitor the daily count of incoming relayed data

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#208]
Alert when going below 70% of normal

Pingping will create an alert to track this. Detecting whether data is complete in a given day.

**Comment by jkarpen** [comment]
@pingpingxiu-DOT-ca-gov may create a new issue that covers this one, may close this one as duplicate.

**Comment by jkarpen** [comment]
Closing as this is redundant with other work being done. Ian will create a separate issue with more details on what needs to happen next.
