### ISSUE TITLE
Meta: Base model optimization

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#211]
Our basal models for VDS data are quite large, and full refreshes of them wind up being pretty expensive, so any optimization of them may be worth our time and money. Some things I'd like to investigate:

Top priority, complete ASAP:
- [x] #212
- [x] #214

Next priority after above completed:
- [x] #213

**Comment by jkarpen** [comment]
Closing this as the subtasks are all complete.
