### ISSUE TITLE
When should we join the VDS raw data with the metadata?

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#214]
We've gone back and forth on this a few times with @kengodleskidot in the context of some of our large aggregations on 30-second VDS data. Some of our downstream metrics depend on detector metadata, which lives in the `STATION_META` and related tables, and not on the raw tables. In order to compute these metrics, we need to join the two tables together on `STATION_ID`.

Normally, we'd do that join as late as possible, so that filtering and especially aggregation can occur, allowing for a cheaper join. For instance, if we join on the 5-minute data, that's 10x smaller of a join than the 30 second data, so we would want to do that if we don't need any of the metadata to do the 5-minute aggregation.

However, a quirk of our base tables is that they are delivered in wide format, with `FLOW_1`, `FLOW_2`, `FLOW_3` ...`FLOW_8`, etc. But not every station has eight lanes of traffic! In fact, the modal one has two or three. So when we do some of our large aggregations, we are doing them on more lanes than exist, wasting a lot of effort.

Right now we are doing the aggregations first, and joining with the metadata second. But we should experiment with joining at other stages! We'd be paying higher costs for the joins, but lower costs on the aggregations.

Example DAGs showing the late join with the metadata:

<img width="1434" alt="image" src="https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/5728311/202c9106-f8c2-40b4-881f-f82f0f81ccdd">

<img width="1434" alt="image" src="https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/5728311/45462f74-b8b5-4d20-aca7-5a474c6782f9">

**Comment by ian-r-rose** [comment]
@JamesSLogan any updates here?

**Comment by JamesSLogan** [comment]
@ian-r-rose I am currently working on reworking the downstream models to use the updated 5 minute-aggregated detector model. One thing that the new metadata gives us access to is `detector_id`, so there are also a few places where joins can make use of this (instead of station id and lane).

**Comment by ian-r-rose** [comment]
I'd be interested to hear your thoughts where `detector_id` could be most helpful! Agree that in many cases it's likely preferable to station-lane.

**Comment by ian-r-rose** [comment]
Ideally, this metadata join should be able to cut down the number of rows in the 5-minute table by a factor of 5 or so by removing non-existent detectors, so I look forward to all our downstream models becoming significantly snappier!
