### ISSUE TITLE
Configuration Diagnostics (Direction Switching)

### ISSUE THREAD

**Issue by kengodleskidot** [cagov/caldata-mdsa-caltrans-pems#224]
In the previous technical committee meeting (5/30/24) one of the members brough up this topic which is discussed in more detail below:

The main reason for this configuration diagnostic is to identify detectors that have incorrect direction configuration information. There are a number of cases where the detector is on the opposite side of the freeway which is in conflict with the configuration information provided by the district. The algorithm described below attempts to automatically identify detectors which are on the opposite side of the road. There may be an opportunity to use geospatial functions to perform this diagnostic so I recommend further discussion on what geospatial tools may be available before diving into creating a model using the algorithm described below:

Each detector in the system is assigned a score between 0 and 100, with zero meaning that it's highly likely that this detector is on the opposite side of the freeway. Since a high number indicates that the detector is very similar to its neighbors in the same direction, this score is usually referred to as Neighbor Affinity.

Conceptually we are looking for detectors that have an hourly flow pattern over a day that doesn't look like the hourly flow pattern from detectors that are upstream and downstream in the same direction. If a pattern is found for a particular detector that more closely matches the detectors on the opposite side of the freeway then a low score is assigned. The details of assigning a score to one particular "target" detector are as follows:

The algorithm is run on a weekday when the flow profiles have strong AM and PM peak direction patterns. Only data during the hours of 5am until 10pm is used (at 3am the flow is similar everywhere).
For the target detector all of its neighboring detectors on both sides of the freeway are selected for 5 miles in each direction.
Only detectors diagnosed as GOOD are used. For the purposes of this calculation, in order for a detector to be GOOD we require that 

1. More than 75% of the individual lane detectors have to be judged good by the daily diagnostic routines 
2. None of the 5-minute flows for any of the lanes during the time period were purely imputed, and 
3. At least 80% of the resulting hourly aggregate data points are good (not imputed).

For each neighbor that has been judged to be good the distance between the target and the neighbor is determined. For distance the mean of the absolute differences between the normalized hourly flow patterns of the two detectors for the day is used. Note that this is done on the aggregate flow across all lanes and that this test is only performed for mainline (ML) detectors.

For the top 10 closest neighbors, as computed by the distance in the preceding step, we count the number of detectors that are in the same direction and we call that K.
The resulting score for this detector is just K / 10. If the top 10 closest neighbors are all on the other side of the freeway then the resulting score will be zero. This is then a pretty good indication that the detector is switched. 

If we don't have 10 neighbors with good data then we use whatever we have. In some cases, we might not have any neighbors with good data. In that case we don't compute a score at all.
Currently this direction switching algorithm in PeMS is done every week on Tuesday night. If the data feed is down for that particular day, then it's possible that we won't be able to compute any scores for any detectors in the system.

**Comment by kengodleskidot** [comment]
The GIS data mentioned in #233 could offer a solution to handling this configuration diagnostic issue using geospatial tools.

**Comment by mmmiah** [comment]
The current PeMS station locations are mostly accurate, however, some of the stations Geo-location are incorrectly configured.  Some of the examples are below-

a. Although stations labeled properly but its geometry is far way from its defined location as shown below for D10 ML 580 freeway-
![image](https://github.com/user-attachments/assets/3f1426f9-c089-441b-a6b2-23c04dac08b7)
b. In some cases, although it should be dual alignment of the road, however, State Highway system used single poly line geometry to visualize both direction of road which makes complexity to use spatial analysis to diagnosis the direction. One of the example is shown below for SH 132 at D10 ML-

![image](https://github.com/user-attachments/assets/04c756dc-1f5a-4d0c-86cf-cb5c3a74109a)

c. Some of the lat and long are incorrectly configured, example, D4 ML Freeway 80

![image](https://github.com/user-attachments/assets/be6ccb5c-3771-4355-9fae-2c079647a795)
![image](https://github.com/user-attachments/assets/7e50b79e-24b0-47ec-a783-419b503a02f6)


d.  New Alignment of Highway while PeMS stations label or lat/long was not updated, Example D10 ML 99
![image](https://github.com/user-attachments/assets/a06b8bc3-1801-49db-8def-b29d432918bb)
![image](https://github.com/user-attachments/assets/6824d963-0900-4a1c-8a4a-8bf2a933de1b)
e. Big Deviation of Station location, example Freeway 108 ML D10 as shown below-
![image](https://github.com/user-attachments/assets/e1ed24af-ab9c-412d-b570-bfad882c1789)
![image](https://github.com/user-attachments/assets/b0df46cd-ac3b-4f40-a725-90c35bbaadc4)
![image](https://github.com/user-attachments/assets/b3d35ee0-20cc-4d60-a91c-9617595af403)

d. Either wrong location or wrong label, example, D3 ML Freeway 89
![image](https://github.com/user-attachments/assets/38c7cfa4-db11-4a36-a744-12ad0c2e7296)

based on my Observation, It is important to request each individual district to collect the lat and long for each station

**Comment by kengodleskidot** [comment]
Great work so far @mmmiah! Let me know if you want to discuss what the list contains so we can hand it off to district staff so they can update their station configuration data as needed. I will also bring this up in my next meeting with Iteris to make sure this is not something caused by any changes/automations they are performing in PeMS.

**Comment by mmmiah** [comment]
Based on further delve of the data. Here is the summary
@kengodleskidot @britt-allen @thehanggit 

1. 727 Stations are lat and long are highly incorrect
[list of PeMS Station that needs lat and long corrections.csv](https://github.com/user-attachments/files/16667068/list.of.PeMS.Station.that.needs.lat.and.long.corrections.csv)
2. Another 1403 stations need to manual edit its location to match the directions and route properly. Here is the list of those 1403 stations-
[incorrect lat and long to match the direction and route properly.csv](https://github.com/user-attachments/files/16667073/incorrect.lat.and.long.to.match.the.direction.and.route.properly.csv)
3. Remaining 20525 stations lat and long are correct. Here are those list-
[Good Quality PeMS stations list.csv](https://github.com/user-attachments/files/16667081/Good.Quality.PeMS.stations.list.csv)

**Comment by mmmiah** [comment]
@kengodleskidot , I found that we have state postmile/absolute postmile for each PeMS station, on the other hand we have beginning and ending postmile in the SHS file (https://gisdata-caltrans.opendata.arcgis.com/datasets/77f2d7ba94e040a78bfbe36feb6279da/explore). I think that for SHS system postmile begin from county boundary lines. Do you know how PeMS defined its state postmile/State Absolute postmile???

**Comment by mmmiah** [comment]
Closed as completed

**Comment by kengodleskidot** [comment]
> @kengodleskidot , I found that we have state postmile/absolute postmile for each PeMS station, on the other hand we have beginning and ending postmile in the SHS file (https://gisdata-caltrans.opendata.arcgis.com/datasets/77f2d7ba94e040a78bfbe36feb6279da/explore). I think that for SHS system postmile begin from county boundary lines. Do you know how PeMS defined its state postmile/State Absolute postmile???

@mmmiah my understanding is that the postmile data in PeMS is brought in with the configuration file data provided by districts. I will share this information with district staff to see the best way to get updates made.

**Comment by mmmiah** [comment]
Updated the Anlysis just for ML and HV with Active stations.
Here is the summary-
 1. out 12287 PeMS stations, 11,500 PeMS stations locations are correct which located within 50ft distance from SHS and matched the route and direction.
 
[Good Quality PeMS stations list.csv](https://github.com/user-attachments/files/16720241/Good.Quality.PeMS.stations.list.csv)

 3.  414 Stations that is within 50 ft have direction and route mismatch,  more breakdown of this 414 stations are : 39 stations did not match with direction and route, 364 direction mismatch only while route is matched, 11 stations route mismatch while direction is right
 
[incorrect lat and long to match the direction and route properly.csv](https://github.com/user-attachments/files/16720240/incorrect.lat.and.long.to.match.the.direction.and.route.properly.csv)

 4. another 337 stations are beyond 50 ft threshold from SHS, needs immediate attention
 
[list of PeMS Station that needs lat and long corrections.csv](https://github.com/user-attachments/files/16720237/list.of.PeMS.Station.that.needs.lat.and.long.corrections.csv)

Here is the [updated map link](https://caltrans.maps.arcgis.com/apps/mapviewer/index.html?layers=f94dc3322f6e48e4b75407595e84aa89)
