### ISSUE TITLE
Missing Station Length Imputation

### ISSUE THREAD

**Issue by mmmiah** [cagov/caldata-mdsa-caltrans-pems#229]
We used length of the station to calculate delay, and vht. This calculated vht again used as the input of q value calculation and q value for tti. The impacts of null station length is like chain reaction impacts. We need to come up with ideas that can impute the missing station length for better quality performance metric calculation. We have around 6281 distinct missing station length out of total 17056 unique station length in five mins performance file. Overall 1/3 of the length is missing which greatly impacts the performance metrics

**Comment by ian-r-rose** [comment]
I'd like to better understand the cause of the missing lengths. Are they for stations that don't have a neighbor within a reasonable distance? Or some data quality issue?

In theory, I think we could also *compute* some of the lengths using the postmiles of neighboring stations, unless I misunderstand the meaning of the field.

**Comment by kengodleskidot** [comment]
Are the missing station lengths for station types ML and HV? I agree with @ian-r-rose that with the absolute postmile data we can compute lengths but I would like to know a little bit more about which stations are missing the length and why. 

For the definition of station length you can review the PeMS User Guide pages 31 and 32:
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/124397677/100c301d-9fd9-4b3a-8407-66064ff58898)
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/124397677/f9f2fce4-fdca-429f-bf7e-6ed8bb6a4b04)

**Comment by mmmiah** [comment]
These are the statistics of missing length from five minutes performance table

![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/166866681/459e0049-e302-4e7c-9060-0f22e42ff18b)

**Comment by ian-r-rose** [comment]
So, this is good, then? If we only expect ML or HV lanes to have lengths, then it seems like they are all populated

**Comment by mmmiah** [comment]
yes, this is expected and we are good in quality of data for performance metrics
