### ISSUE TITLE
How to Fill in Data Holes

### ISSUE THREAD

**Issue by kengodleskidot** [cagov/caldata-mdsa-caltrans-pems#232]
When we receive 30 second data from the TMC's we have three scenarios to solve when it comes to missing or more than expected samples. In the first scenario, if we receive no samples during a five-minute timeframe, then imputed values are calculated and used. In the second scenario, if we have missing samples i.e. less than 10 samples received during a five-minute period then currently PeMS normalizes the flow value and the average of the actual observed occupancy values are used, see the following image for additional details:
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/124397677/2a2ef2a1-ba0d-43df-bef0-c682b91252ad)

The third scenario is when we receive more than 10 samples during a five-minute period. This scenario occurs but is not discussed in any of the PeMS documentation that I have come across. Below is a screenshot showing the number rows by sample count in the five_minute_aggregate model from 6/7/24 for reference:
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/124397677/40b04704-1351-4ef3-864d-a89309e93e7f)
For the third scenario, I will have a discussion with Iteris and former Caltrans PeMS staff to understand why this happens and how PeMS currently handles the third scenario so we can update our model if needed. 

We are currently working on the imputation models to deal with the first scenario. For the second scenario, the current five_minute_aggregate model does not contain any normalization for flow. I recommend we update the five-minute model to account for the normalization of flow when less than 10 samples are provided.  I believe the occupancy and flow weighted speed values can remain as is. Does the group have any other thoughts on how to handle the second scenario?

**Comment by ian-r-rose** [comment]
@kengodleskidot would you be interested in working on normalizing the five minute aggregate model to do this?

**Comment by kengodleskidot** [comment]
Based on my investigation including discussions with Iteris, the > 10 samples per 5-minute interval do not appear to be duplicates but rather the TMC's sending more samples associated with shorter time increments. For example, sending 3 samples taken every 10-seconds in a 30-second file instead of 1 per station. The detectors that are sending > 10 samples per 5-minute increment also seem to be concentrated for stations in districts 3 and 7 so this may be something Caltrans staff can reach out to the TMC's on to see if there is room for optimization.

I am concerned with normalizing 1 or 2 samples and below is an example I ran into during QA/QC:
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/124397677/852c502c-ae78-45c7-8599-50730fd9d423)
For the 17:05 timeframe you can see that each original flow value was multiplied by 10 resulting in a lane 2 normalized flow value that was particularly high. I believe an upper limit on normalized flow would make sense in this situation and will be a topic we discuss in an upcoming PeMS technical committee meeting.

I would be interested (and am already working on a branch) to incorporate normalization as part of the 5-minute station aggregation model. When I create the 5-minute station aggregation model I will include this level of detail and reference this issue.

**Comment by kengodleskidot** [comment]
PR #342 will address normalizing observed data and #316 will address filling in the remaining data holes with imputed data

**Comment by kengodleskidot** [comment]
PR #342 has been merged and #316 has been closed.
