### ISSUE TITLE
Relay Server Issue - The Crawl Queue Builds up

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#237]
Over the last week, the crawl queue starts to build up and exceeded the normal range.  

![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/bc8242a7-043b-4b31-b595-5f9cf0fae8e4)

This indicates the relaying is malfunctioning. 

FYI the dashboard for relay operation is here
http://svgcmdl02:5601/app/dashboards#/view/4438c280-fcfd-11ee-99ff-69aa747c5773?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-3w,to:now))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'Crawling%20Operation',viewMode:view)

Troubleshooting

**Comment by pingpingxiu-DOT-ca-gov** [comment]
@ZhenyuZhu-Caltrans 
@ian-r-rose

**Comment by pingpingxiu-DOT-ca-gov** [comment]
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/7d302dc2-f809-493c-a08d-a5b74e40cbaa)

A simple restart seems getting the service back to normal. 

This needs to be kept watching. If such glitches keep occurring, 
we may either 
(1) Set up periodic restart procedure to get around of it, or
(2) Deeper look at why it sometimes hanging, needing a restart

**Comment by pingpingxiu-DOT-ca-gov** [comment]
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/149613649/f290081b-02f6-4d4a-9a6b-983ff38b9a7e)
So the backfill crawl queue finished

**Comment by ian-r-rose** [comment]
Closing, as this incident has been resolved
