### ISSUE TITLE
Create incremental model without hard-coded dates for regression coefficients

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#239]
In #234 and #209 we created a table of regression coefficients for imputation. That table could use some improvements:

1. It should make use of `pems_clearinghouse_start_date` to determine when to start
2. It shouldn't have hard-coded dates
3. It should be incremental so that as time goes, we can continually update the coefficients with new values

@mmmiah since you've been thinking about how often to compute the regression coefficients, would you be interested in taking this one on?

**Comment by mmmiah** [comment]
@ian-r-rose, I can try, but feel free to assign 2nd expert person with me in case I need help!
