### ISSUE TITLE
Consolidate local and regional regression models

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#240]
The models for local and regional regression are extremely similar (and rightly so, since they do more-or-less the same thing, just drawing from different pools of stations for regression!). It is probably possible to combine them to one model with columns for both local and regional regressions.

@mmmiah would you be interested in looking into this?

**Comment by mmmiah** [comment]
@ian-r-rose , sure!

**Comment by mmmiah** [comment]
@ian-r-rose , I think that we also want to consolidate the global one, once you are done!

**Comment by ian-r-rose** [comment]
Agreed, we should look at that one next!
