### ISSUE TITLE
Data Relay - How to backfill the missing data with duplicate handling in the downstream DBT model

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#244]
## Summary

We need to handle the data backfilling as a common operational need. Right now the data backfilling
mechanism is not implemented, so we cannot fill the missing data with the correctness guarantee. 

## Question 1, Why data is missing? 
Incidents on Data Relay and district-level ETL will cause the data to discontinue for certain amount of time. 
And in addition, it occurs one or two times in a month. We need to fill the missing data.

## Question 2,  Why simply backfilling the missing data does not work? 
Suppose we have 3 days gap (missing data), in order for us to fill the data in entirety, we need to have 1 day
margin before and after those 3 days gap (so five days' worth in total). That lead to duplication. 

Right now the downstream DBT model supports incremental model. However, if the incremental is not occurring
in the right chronological order, there will be serious data quality issues propagated downstream: 

Since there is no indication of in-order v.s. out-of-order incremental portion, 
the system may either treat all "out-of-order" as "in-order", or treat all "in-order" as "out-of-order". 
They have respective problems: 

(1) When the system treat "out-of-order" as "in-order", it will produce wrong results because "out-of-order" 
data will impact more downstream updates than "in-order" and treating them as "in-order" will fail to 
update all the places. 
    If we want to avoid the wrong results, we may have to resort to option (2)

(2) When the system treat "in-order" as "out-of-order", it may implicate full model calculation every time, 
and it will defeat the whole purpose of doing "incremental."

## Conclusion

Therefore neither option will be viable for us. We need to think through on this problem, and come up with 
right mitigation plan. 

@ian-r-rose 
@ZhenyuZhu-Caltrans

**Comment by ian-r-rose** [comment]
What guarantees can you put on the files that are uploaded to S3? It would be much easier to reason about backfilling if all files labeled as coming from a particular date and district. That is to say, it would be fine if the files *within* a given day have some overlap, but if we can say that all files from, e.g. 2024-04-30 contain samples from that date and only that date, it would be much easier to do backfills.

This is also why it's generally a good practice to make sure that tasks are (1) idempotent, and (2) able to be run for specific dates. For instance, this is what Airflow encourages. Early in this project, we had planned to use Airflow for this data relay effort. Do your current scripts allow for idempotent re-runnable tasks?

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Today we reached a consensus on the backfilling mechanism: 

* Backfilling should clean the old Snowflake data before publishing new data. 
* The backfilled data should be validated (in terms of completeness).

This will be resulted in an Airflow DAG that consists of multiple components. 
I suppose the work be tracked here?

@ian-r-rose @ZhenyuZhu-Caltrans

**Comment by jkarpen** [comment]
Closing this as a consensus was reached. Next step will be implementing the process. @pingpingxiu-DOT-ca-gov will create a new issue for the follow-on work required.
