### ISSUE TITLE
Tracking XML Configuration changes in downstream ETL

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#245]
PeMS Station/detector/controller config table only show current snapshot. 

We may need to go back in history for analytics as well. 

In order to do that, DBT model need to support tracking those slowly changing data's evolution.   

@ian-r-rose @ZhenyuZhu-Caltrans

**Comment by jkarpen** [comment]
This issue may no longer be needed, @ian-r-rose and @pingpingxiu-DOT-ca-gov will meet to discuss further and close if that's the case.

**Comment by ian-r-rose** [comment]
We think this is no longer necessary, there seems to be enough data in the config and log tables to support time-travel. Follow-up work will be done in #273
