### ISSUE TITLE
Bottleneck Delay

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#256]
**Bottleneck Delay**: The delay is simply the sum of the individual PeMS segment delays for the entire duration and spatial extent of the bottleneck. The delay is calculated with respect to a threshold speed of 60 mph.
We then allow users to see summary tables of the top bottlenecks in a region sorted by the number of days activated, or any other available measure. In addition we allow users to see the bottlenecks on the maps.

@kengodleskidot says the final table would have the following columns: timestamp (5-min level), station id (the one at the start of the bottleneck), district, extent, all delay cols summed (35, 40, 45, 50, 55, 60)

Related to issue #186 and issue #255

**Comment by britt-allen** [comment]
@kengodleskidot can you clarify the scope of this metric a bit more. 

My current understanding is that I would be summing the `delay_60mph` column over instances where the `bottleneck_start` and `spatial_extent` columns are true. Is that correct? Am I missing other variables?

What is unclear to @ian-r-rose is it says "for the entire duration and spatial extent of the bottleneck" – how do we identify a bottleneck through space and time.

**Comment by britt-allen** [comment]
@kengodleskidot says the final table would have the following columns: timestamp (5-min level), station id (the one at the start of the bottleneck), district, extent, all delay cols (35, 40, 45, 50, 55, 60)

**Comment by britt-allen** [comment]
Are we looking at an aggregation of delays per day @kengodleskidot?

**Comment by thehanggit** [comment]
@kengodleskidot Please add the delay metric into station aggregation five minutes level so I can calculate the delay in the bottleneck model.

**Comment by jkarpen** [comment]
This is currently blocked by #380
