### ISSUE TITLE
Fix nightly build error

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#265]
The nightly job failed over [here](https://california.getdbt.com/deploy/6/projects/10/runs/3738/). It looks like it is a syntax error in `int_clearinghouse__station_agg_five_minutes`, probably due to the initial full refresh templating in differently from what is in the incremental logic. @britt-allen would you be able to take a look?

**Comment by britt-allen** [comment]
Taking a look

**Comment by britt-allen** [comment]
I am not seeing an extra parentheses anywhere, but will keep digging

**Comment by britt-allen** [comment]
Yeah I looked at the macro in dbt cloud and couldnt see where the syntax error would be for a full refresh. I am trying to find the nightly job query in Snowflake and am having trouble there too 😓

**Comment by britt-allen** [comment]
Figured out where to see the compiled code in dbt cloud. Also figured out how to see it in Snowflake with Ian's help :)
