### ISSUE TITLE
Create a final combined imputation model

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#271]
For the local, regional, and global imputation methods we have been storing the results in separate columns. This allows us to compare the results of different imputation methods.

That said, we also want to select one of the methods for each timestamp to use as our preferred value in downstream metrics calculations. Roughly speaking, we want the following prioritization:

1. Device-reported values if we consider them reliable
2. Local imputation
3. Regional imputation
4. Global imputation

Our final model should just have a single column for each of volume, occupancy, and speed. In addition, we want the following columns:

1. `observed`, boolean, indicating whether the value is observed or imputed
2. `imputation_method`, indicating which (if any) imputation method is used
3. `regression_date`, indicating the date that the regression coefficients were computed (if applicable)

At the end of the day, this model should look almost identical to `int_clearinghouse__detector_agg_five_minutes`, but with the additional columns indicating imputation info. This will make it easier to swap this new model into all of our downstream performance metrics.

@mmmiah are you interested in taking this one on?

**Comment by mmmiah** [comment]
@ian-r-rose , yes, I can work on this.

**Comment by kengodleskidot** [comment]
What are your thoughts on having the device reported values (observed) as it's own model and updating the `int_clearinghouse__detector_agg_five_minutes` model to contain the same values (plus the three new columns mentioned above) it currently has with the only difference being that the flow, occupancy, speed and sample count values would be populated with the results of the observed and imputed models based on the hierarchy in the initial comment? We can have a quick meeting to discuss (pros/cons) this if you'd like @ian-r-rose and @mmmiah.

**Comment by ian-r-rose** [comment]
I'm not sure I understand your proposal @kengodleskidot, wouldn't that be mostly the same thing as creating a new model for final imputed values, and keeping `int_clearinghouse__detector_agg_five_minutes` as the device-reported ones?

**Comment by kengodleskidot** [comment]
@ian-r-rose Yes, except that we would not need to change the other downstream model references to a new model since `int_clearinghouse__detector_agg_five_minutes` would have the "final" observed/imputed value based on the best data available. Creating a new model for the "final" values also works but just requires changing references in downstream models.

**Comment by ian-r-rose** [comment]
> @ian-r-rose Yes, except that we would not need to change the other downstream model references to a new model since `int_clearinghouse__detector_agg_five_minutes` would have the "final" observed/imputed value based on the best data available. Creating a new model for the "final" values also works but just requires changing references in downstream models.

I don't think it's a big deal to change the downstream model references, it's mostly needed in two or three places. I just searched for usage in the project and came up with the following:

```
models/intermediate/clearinghouse/int_clearinghouse__station_agg_five_minutes.sql:    from {{ ref('int_clearinghouse__detector_agg_five_minutes') }}
models/intermediate/diagnostics/int_diagnostics__constant_occupancy.sql:    from {{ ref('int_clearinghouse__detector_agg_five_minutes') }}
models/intermediate/imputation/int_imputation__detector_agg_five_minutes.sql:    select * from {{ ref('int_clearinghouse__detector_agg_five_minutes') }}
models/intermediate/imputation/int_imputation__global_coefficients.sql:    select * from {{ ref('int_clearinghouse__detector_agg_five_minutes') }}
models/intermediate/imputation/int_imputation__local_regional_regression_coefficients.sql:    select * from {{ ref('int_clearinghouse__detector_agg_five_minutes') }}
models/intermediate/performance/int_performance__detector_metrics_agg_five_minutes.sql:    select * from {{ ref('int_clearinghouse__detector_agg_five_minutes') }}
models/intermediate/performance/int_performance__max_capacity.sql:    from {{ ref('int_clearinghouse__detector_agg_five_minutes') }}
```

Several of those we don't want to update because they are involved in diagnostics, the rest should be pretty straightforward. From a code clarity perspective, I think I'd appreciate having `imputation` be in the name of the model, so that the fact that it includes synthetic data is obvious to consumers of the data.
