### ISSUE TITLE
Use status column in config tables to handle decomissioning of stations/controllers/detectors

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#273]
The config log tables have a "status" column, which seemingly indicates when a station has been decomissioned. Right now, we are not using that column in our SCD-2 tables, so our metadata tables have some devices which are not currently active.

We should use the "status" column to determine when a station is no longer active and ensure that those stations do not show up in the final tables (or are easy to filter out)

**Comment by kengodleskidot** [comment]
Thanks for bringing this up @ian-r-rose and I will check the status column in our new tables against what I see in the current PeMS to confirm your observation initially mentioned.

**Comment by ian-r-rose** [comment]
@britt-allen pending the results of @kengodleskidot's investigation, would you be able to take a look at this?

**Comment by britt-allen** [comment]
I will be able @ian-r-rose

**Comment by britt-allen** [comment]
@kengodleskidot can you share the results of your investigation, please?
