### ISSUE TITLE
Deduplicate data relay VDS data

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#274]
The 30-second data relay data may sometimes contain duplicate sample data, especially if we are recovering from incidents or backfilling.

We should insert some logic into the staging model to deal with this possibly-duplicated-data.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
I'm thinking of using snowsql to do that. 
Approach 1: a sql query to drop the samples with duplications. 
Approach 2: create a new table, so the deduped data will be in the new table, rather than in-place removal as Approach 1.

What's your thoughts? @ian-r-rose

**Comment by pingpingxiu-DOT-ca-gov** [comment]
https://github.com/cagov/caldata-mdsa-caltrans-pems/blob/ed2605f906e30bb5c9c788bdd90dc46e6c09f019/transform/models/intermediate/diagnostics/int_diagnostics__real_detector_status.sql#L7-L16

**Comment by ian-r-rose** [comment]
Closing as completed by #304
