### ISSUE TITLE
Document the data relay process

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#279]
This issue will be for tracking any documentation needed for the data relay server.

- [ ] Pingping gave a great presentation on this process so I think most of the narrative documentation can borrow from that presentation. You can add your docs **[here](https://github.com/cagov/caldata-mdsa-caltrans-pems/blob/main/docs/data/data-relay.md)**. The goal for this issue is to convert the presentation Pingping gave into project documentation.
- [ ] Document a process for identifying and dealing with data quality issues caused by either the data relay or other causes.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
I'm taking the issue working on it.
