### ISSUE TITLE
Document intermediate clearinghouse model

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#286]
The `int_clearinghouse__station_agg_five_minutes` [model](https://california.getdbt.com/accounts/6/develop/3012/docs/index.html#!/model/model.caldata_mdsa_caltrans_pems.int_clearinghouse__station_agg_five_minutes) is missing a description.

**Comment by kengodleskidot** [comment]
@britt-allen I do not see this model in the intermediate->clearinghouse folder: 

![Image](https://github.com/user-attachments/assets/e23e5615-fdfe-4d24-9a90-f7d1c3a41477)

Do you know if this model is being recreated? I do see that the `int_clearinghouse__active_stations` model needs to be documented so I will work on that for now.

**Comment by britt-allen** [comment]
Sounds good! Must have been deleted. Thanks for working on the other model's documentation.
