### ISSUE TITLE
Create Snowflake Training Document and Content

### ISSUE THREAD

**Issue by melanie-logan** [cagov/caldata-mdsa-caltrans-pems#29]
Create Snowflake training Document and Content.

Training should include topics below:

- How to load data
- For Analysts: How to use Snowflake to look at raw/transform tables, how dbt connects to Snowflake, and how to use Snowflake worksheets for testing queries before dbt modeling
- [Melanie Logan](mailto:melanie.logan@innovation.ca.gov) might be able to take first pass at creating Snowflake content? Britt will check in with her

---
- [x] Create content outline
- [x] Create training document
- [x]  Create training worksheet(s)
- [x] Create training Slides

**Comment by jkarpen** [comment]
@melanie-logan I noticed this issue is not in the DSE Sprint Planning project but it is still listed as open in the Caltrans repo. Can I close this one or are you still working on it?
