### ISSUE TITLE
Delete two unused models

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#294]
Can see in the lineage graph [here](https://california.getdbt.com/explore/6/projects/10/environments/production/lineage/) that model `int_clearinghouse__most_recent_station_meta` and `int_clearinghouse__most_recent_station_status.sql` are unused. Ian and Britt agreed on a call to delete them.

**Comment by jkarpen** [comment]
@britt-allen Can you specify the model names to be deleted in the description above?

**Comment by britt-allen** [comment]
I do not know, I did not write this issue.

Best,

Brittany Allen (she/her)
Senior Analytics Engineer, CalData | CA Office of Data & Innovation
916-270-4718 | ***@***.***
Follow us: About CalData <https://innovation.ca.gov/who-we-are/caldata/> | ODI
Work <https://innovation.ca.gov/our-work/projects/> | ODI blog
<https://innovation.ca.gov/blog/> | ODI Twitter
<https://twitter.com/californiaodi>

**Comment by ian-r-rose** [comment]
@britt-allen you did write this issue

**Comment by britt-allen** [comment]
Unclear what other model needed to be deleted, perhaps next time we prioritize fully filling out the issue and making sure we are in agreement rather than rushing and leaving in placeholder variables.

**Comment by britt-allen** [comment]
@kengodleskidot, @pingpingxiu-DOT-ca-gov, and @ian-r-rose based on our lineage graph here it looks like we are not using the circled (in red) resources. what are y'alls thoughts on removing those from the project as well?

![Image](https://github.com/user-attachments/assets/84f6dd5f-41da-42ac-8c24-d54b3d279c3a)

**Comment by ian-r-rose** [comment]
We do need those two models, they will be used in an additional 1-2 diagnostic tests.

The ones we no longer need are `int_clearinghouse__most_recent_station_meta` and `int_clearinghouse__most_recent_station_status`

**Comment by ian-r-rose** [comment]
Sorry, was a bit imprecise above. I don't know whether we need that counties/cities seed files (I think @kengodleskidot added them in anticipation of doing some final labeling of county/city codes).

But the `controller_config` model is intended to be used in an additional diagnostic condition (the "Controller Down" one indicated in #78). @kengodleskidot could you open a new issue describing what needs to be done for that diagnostic?
