### ISSUE TITLE
Document Bottlenecks

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#295]
Information about this is scattered across issues, PRs, comments within models, and dbt docs. Synthesizing this in narrative form could be helpful for future and current team members to reference.

**Comment by kengodleskidot** [comment]
Let me know if you want to get together for any of this.

**Comment by britt-allen** [comment]
sure, does tomorrow from 11-11:30 work for ya?

Best,

Brittany Allen (she/her)
Senior Analytics Engineer, CalData | CA Office of Data & Innovation
916-270-4718 | ***@***.***
Follow us: About CalData <https://innovation.ca.gov/who-we-are/caldata/> | ODI
Work <https://innovation.ca.gov/our-work/projects/> | ODI blog
<https://innovation.ca.gov/blog/> | ODI Twitter
<https://twitter.com/californiaodi>

**Comment by kengodleskidot** [comment]
![image](https://github.com/user-attachments/assets/7ec6a9b8-2ea2-4651-a748-445fc6f341d8)
