### ISSUE TITLE
Rebuild `int_clearinghouse__nearby_stations`

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#296]
Now that we have a better version of the metadata in `int_vds__station_config`, let's rebuild `int_clearinghouse__nearby_stations` into one based on the new metadata (probably named `int_vds__nearby_stations`).

This, along with #294 would remove most references to `int_clearinghouse__station_meta`.

**Comment by mmmiah** [comment]
@ian-r-rose meta_date is missing in 'int_vds__station_config' which is required for 'int_vds__nearby_stations' model. Any idea who worked on 'int_vds__station_config' and can add meta date similar like 'stg_clearinghouse__station_meta'? This will help us to update int_vds__nearby_stations

**Comment by ian-r-rose** [comment]
@mmmiah you should be able to use `time_id` or `valid_from` to serve the same purpose that `meta_date` did in the old model

**Comment by mmmiah** [comment]
@ian-r-rose , accepted your suggestions, rebuilt the model, updated ymal and upstream model. Please have your review and merge if everything looks good. Then I will delete the existing old model 'int_clearinghouse__nearby_stations'. Thank you!

**Comment by jkarpen** [comment]
Closing,l fixed by #320
