### ISSUE TITLE
Investigate change in bottlenecks query performance

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#298]
After #291 the `int_performance__bottlenecks` model has become our most time-consuming model. It's not obvious to me what the issue is, but one clear change is that it is now processing _a lot_ more data (~185MM rows [now](https://app.snowflake.com/vsb79059/dse_caltrans_pems/#/compute/history/queries/01b5a8e6-0002-a127-003e-388700a3b0de/profile?autoRefreshInSeconds=0), ~6MM rows [before](https://app.snowflake.com/vsb79059/dse_caltrans_pems/#/compute/history/queries/01b58183-0002-97c6-003e-38870098ef36/profile?autoRefreshInSeconds=0)). Has something gone wrong with the join or incremental logic? Which one is correct?

@britt-allen would you be able to investigate?

**Comment by kengodleskidot** [comment]
@britt-allen let's take a look at this tomorrow (7/16/24) during our bottlenecks meeting.
