### ISSUE TITLE
Remove all references to `int_clearinghouse__station_meta`

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#310]
We now prefer `int_vds__detector_config` to `int_clearinghouse__station_meta`. After #291 we should be able to remove any remaining references to the latter.

**Comment by jkarpen** [comment]
@JamesSLogan reach out to @ian-r-rose for more info on this task if you have questions.

**Comment by tnrahim** [comment]
@JamesSLogan Have you started any work on this?

**Comment by JamesSLogan** [comment]
@tnrahim Negative

**Comment by tnrahim** [comment]
Sounds good! It looks like is related to the current issue I'm working so I hope you don't mind if I take it on :).

**Comment by tnrahim** [comment]
Updates:
Removed int_clearinghouse__station_meta  references using pull request #318. Currently resolving CI errors prior to merging.
