### ISSUE TITLE
Create mart for imputation report

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#311]
Now that we have our imputation methods mostly implemented, we should create a summary table based on the one in #297 . For each station and date, we could have:

* % observed
* % of each imputation method
* % unobserved and unimputed (i.e., values that are still null after all our attempts to impute)

This table could be further aggregated in a BI tool to freeway, district, county, etc.

@mmmiah would you be interested in taking this one on?

**Comment by mmmiah** [comment]
Yes, I can work on this

**Comment by mmmiah** [comment]
closed as completed
