### ISSUE TITLE
which speed column to use in int_imputation__detector_imputed_agg_five_minutes

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#312]
There are currently two speed cols in `int_imputation__detector_imputed_agg_five_minutes` should we delete one of them?

**Comment by mmmiah** [comment]
@britt-allen Based on my code review back and fro, It seems that we used 'speed_five_mins' not the 'weighted_speed'. Timely catch, I will go ahead and update the model now. Thanks!

**Comment by jkarpen** [comment]
This is closed by #315
