### ISSUE TITLE
Fill in timestamp gaps in imputation

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#316]
The imputation model is good at imputing data for timestamps that have bad or `null` data, but it currently doesn't fill in gaps if there is *no data reported at all*. So if a detector has a few hours where there are no data samples reported, and the timestamps don't exist in the raw data, then we won't impute for that gap. In practice, this does happen.

The task here is to fill in gaps in both stations and timestamps prior to imputing the data. This might be expensive, so doing it in a cost-effective way might be tricky. I would expect filling in station gaps to rely on some of the work @tnrahim is doing in #318.

**Comment by JamesSLogan** [comment]
Status update: created a timestamp spine and generalized it into a macro in case it becomes useful in the future. Am working on an `AS OF` join using this spine. There is 1 detector, in production, that has _more_ than the expected 288 samples/day, which may be due to an upstream bug.
