### ISSUE TITLE
Marts: do some spatial aggregation

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#319]
We currently have VDS data aggregated to different temporal levels (five minute, hourly, daily, weekly, monthly). We don't yet have any data models aggregating the data to different spatial levels. The following might be helpful models to make:

* Aggregate to freeway-direction-station-type
* Aggregate to district
* Aggregate to county
* Aggregate to city

@kengodleskidot does this sound like a useful set of models? If so, would you be interested in taking it on?

**Comment by jkarpen** [comment]
Closing this as complete per @mmmiah
