### ISSUE TITLE
Bugs in imputation logic

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#326]
1. There is a bug in the imputation_method column for the `int_imputation__detector_imputed_agg_five_minutes` model. Right now it's reporting observed for every row when it's clear that some have been imputed.

```sql
select VOLUME_IMPUTATION_METHOD, count(*) as a_count
from transform_prd.imputation.int_imputation__detector_imputed_agg_five_minutes
where "STATION_ID" = '826789'
and "SAMPLE_DATE" = '2024-07-17'
group by VOLUME_IMPUTATION_METHOD
```

2. Speed is 0 when volume and occupancy are non-zero, we should be imputing for speed in this case but we are not

```sql
select *
from transform_prd.imputation.int_imputation__detector_imputed_agg_five_minutes
where "STATION_ID" = '826789'
and "SAMPLE_DATE" = '2024-07-17'
and "OCCUPANCY_AVG" > 0 and "VOLUME_SUM" > 0 and "SPEED_FIVE_MINS" = 0
```

Here's a [snowflake worksheet](https://app.snowflake.com/vsb79059/dse_caltrans_pems/w4BKFk3md5jB#query) to reproduce both 1 and 2 as well, the code in the worksheet is the same as the snippets above.

**Comment by mmmiah** [comment]
We did not imputed any values for good detectors that's why you are seeing all observe.

**Comment by britt-allen** [comment]
Do you think a detector should be labeled as good when speed is zero, but volume and occupancy are non-zero? @mmmiah

**Comment by mmmiah** [comment]
@britt-allen  this is great point to discuss with the team in our upcoming meeting. I think that the detector status was reported for whole day, while our imputation is for five minutes level. now for any time windows within a particular day the detector may not be good. I see the potential to identify the detector status in more micro time windows like every five minutes. We did not define the status in imputation phase of the modeling. I think that it is time to think about the modification of detector status in every five minutes interval.

**Comment by mmmiah** [comment]
@ian-r-rose @britt-allen After my investigation. I found that all tagging is correct. We did tag observe for following cases-

1. Detector is good
2. Detector is bad but still speed/volume/occupancy is null (none of the imputation was able to impute), Please have the code review for details in 'int_imputation__detector_imputed_agg_five_minutes'

![image](https://github.com/user-attachments/assets/2b5d72fb-0607-4d84-96bf-a81a8072d24a)

Test code is here: https://app.snowflake.com/vsb79059/dse_caltrans_pems/w1UXlg4GbIXK#query

It seems that only I need to fix the application of downstream model. We need to make sure that We are also imputing good detectors null speed and volume and occupancy is not null! Let me know if you have further suggestions. Thank all for investigating the data QC

**Comment by britt-allen** [comment]
I agree we should still address the instance where speed is null and volume and occupancy are not

**Comment by jkarpen** [comment]
@britt-allen created issue #341 to track follow-on work related to this. She will close this once some additional testing is done.
