### ISSUE TITLE
SImplify the config table relay

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#327]
* Talked with Ian, we need to bypass kafka for config tables relay. 
* First option is, a simple cron job that runs 4 times per day on the machine of Oracle Puller.
* Pingping tried and failed. The challenge is, that machine is old and installing Snowsql faced difficulties. 
* Then using the second option, using shared network-drive in lieu of Kafka for data transfer between Oracle Puller and Uploader. 
* Tried and worked with a minor bug on date conversion.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
@ian-r-rose 
I tried yesterday and the tricky thing with using Oracle Puller machine for uploading directly to snowflake is, 
it is too old, and installation of snowsql, a relatively new software, has difficulties. 

Therefore, we need to adopt the two machine approach, and explore the way to avoid duplications. I tried your next option - using network shared drive for data transfer, works. I need your help on the date format conversion.

**Comment by ian-r-rose** [comment]
Great, thanks for the update @pingpingxiu-DOT-ca-gov! I can meet before 9 or after our sprint check-in to take a look at the date format.

**Comment by ian-r-rose** [comment]
Hi @pingpingxiu-DOT-ca-gov I see that file copies have resumed, is this resolved on your end?

<img width="941" alt="image" src="https://github.com/user-attachments/assets/192d76e0-e0a5-40d4-8b1e-d1c996124aba">

**Comment by jkarpen** [comment]
Ian and Pingping confirmed this has been resolved so closing this issue.
