### ISSUE TITLE
Training session: Role/Database Architecture in Snowflake

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#339]
The goal for this is to give Caltrans a walkthrough of the role/database architecture in Snowflake. 

Prior art developed by Ian for CARB, should be able to make use of this with some light editing: https://docs.google.com/presentation/d/1NkOVQ-KKp_h7-B0E7VnJ48MDz5eUQFJ45CJq1QS6xFc/edit#slide=id.gd01156d741_1_3

**Comment by britt-allen** [comment]
Hey Josh can you reach out to the Caltrans team to schedule a session on this for Thursday or Friday of next week. I'll need @JamesSLogan on as back up.

**Comment by britt-allen** [comment]
@JamesSLogan can you review and provide feedback on the slides please: https://docs.google.com/presentation/d/1NkOVQ-KKp_h7-B0E7VnJ48MDz5eUQFJ45CJq1QS6xFc/edit#slide=id.gd01156d741_1_3

**Comment by JamesSLogan** [comment]
@britt-allen done! I made some revisions to the transformer and reporter role descriptions on the "Snowflake architecture: roles" slide. Everything looks good

**Comment by britt-allen** [comment]
Thank you James!
