### ISSUE TITLE
Caltrans training: Create snowflake training document, content, and exercises

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#34]
@melanie-logan  to fill in the remaining details for this issue

Reference: [Caltrans training plan](https://docs.google.com/document/d/1V8kJOVpsOfpRy_vkiCvPNAIYST0lNgsnfEFo7C_ZUb8/edit?pli=1)

----

Notes:

Training should include topics below:

- How to load data
- For Analysts: How to use Snowflake to look at raw/transform tables, how dbt connects to Snowflake, and how to use Snowflake worksheets for testing queries before dbt modeling
---
- [ ] Create content outline
- [ ] Create training document
- [ ]  Create training worksheet(s)
- [ ] Create training slides

**Comment by britt-allen** [comment]
Ian has some exploratory models here: https://github.com/cagov/caldata-mdsa-caltrans-pems/tree/exploratory-models, may be helpful when developing the exercise material for Snowflake worksheets

**Comment by jkarpen** [comment]
@melanie-logan is this still in progress?
