### ISSUE TITLE
Partition `diagnostics__detector_daily_detail` unloading

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#344]
We are getting the following error in our nightly build:

```
Database Error in model diagnostics__detector_daily_detail (models/marts/diagnostics/diagnostics__detector_daily_detail.sql)
  100083 (22000): Max file size (536870912) exceeded for unload single file mode. We recommend that you increase the max file size parameter, or disable single-file mode in the unload command and combine the unloaded files into a single file after you download them.
```

This is because we are hitting a size limit when trying to unload the `diagnostics__detector_daily_detail` table to parquet (cf #329). This is good, and expected! Best practices for parquet are to partition the data once it gets larger than a couple hundred megabytes. For this table, I think a natural thing to partition by would be month, so each month of data would be in its own file. Would that work for your purposes @kengodleskidot?

**Comment by ian-r-rose** [comment]
Note that an example of how to do a partitioned unload is here: https://github.com/cagov/caldata-mdsa-caltrans-pems/blob/9627ac607b74c97b845301e3aef2457e69e4010e/transform/models/marts/performance/performance__station_metrics_agg_daily.sql#L3

It's possible that exactly the same line would work for `diagnostics__detector_daily_detail`

**Comment by kengodleskidot** [comment]
I agree that a partition by month/year would work, thank you Ian.
