### ISSUE TITLE
Review/Finalize Caltrans project charter

### ISSUE THREAD

**Issue by jasonlally** [cagov/caldata-mdsa-caltrans-pems#35]
Resolving final questions/clarifications in the project charter. 

Update 1/4/2024:
Only remaining question is getting more detail from Caltrans on the datasets they listed as in scope beyond the core PeMS dataset. Need follow-on meetings with them to get more info on how these fit into the overall project.

**Comment by jkarpen** [comment]
Assigning this to @jasonlally, next step is Jason will send this for signatures with Docusign.

**Comment by jasonlally** [comment]
This is signed and filed in our project folder now - closing
