### ISSUE TITLE
Make slim CI work better

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#352]
We currently use "Slim CI" for this project, which (in theory), only runs models that are *affected* by a PR in CI. The intention here is that we can save time and money by just running the stuff that needs to be run. It works by comparing the code in the branch with that in the nightly production job, and identifying ones where there is a diff.

This is not working as intended because of the way we do some different logic depending upon whether we are "dev" or "prd". In particular, we select *less* data in dev for a lot of our larger models to improve the developer experience for those models. Unfortunately, this means that there _is_ a real difference between dev and prod, even if the pre-rendered model has not changed, thus creating some [false positives](https://docs.getdbt.com/reference/node-selection/state-comparison-caveats#false-positives) in our slim CI job.

I'm not sure of the best way to fix this right now.

**Comment by jkarpen** [comment]
Assigning to @kengodleskidot to review and see if he has any thoughts on how to move forward on this one.

**Comment by jkarpen** [comment]
We put this in the backlog until @ian-r-rose returns to get his input on how to handle this item.

**Comment by jkarpen** [comment]
Summer will tackle this research project, will assign once she is added to the right GitHub team.

**Comment by summer-mothwood** [comment]
Note: the dbt documentation page on state modified caveats have been updated a few times over the last few weeks, with some changes that might specifically address our issue -- but would require a version upgrade from dbt 1.7.18 (current Caltrans dbt version) to dbt 1.9+ or dbt Versionless. 


* https://github.com/dbt-labs/docs.getdbt.com/pull/6207

> Beginning in dbt Core 1.9, when you set the `state_modified_compare_vars` [behavior flag](/reference/global-configs/behavior-changes#behavior-change-flags) to `True` and a model uses a `var` or `env_var` in its definition, dbt will identify that lineage in such a way that it will include the model in `state:modified` when the `var` or `env_var` value has changed. 


* https://github.com/dbt-labs/docs.getdbt.com/commit/cb69cf640a0fa91b52488669fd28c3ecae860b1d

> You need to build the state directory using dbt v1.9 or higher, or [Versionless](/docs/dbt-versions/versionless-cloud) dbt Cloud, and you need to set `state_modified_compare_more_unrendered_values` to `true` within your dbt_project.yml.
If the state directory was built with an older dbt version or if the `state_modified_compare_more_unrendered_values` behavior change flag was either not set or set to `false`, you need to rebuild the state directory to avoid false positives during state comparison with `state:modified`.


I'm still looking into this, but wanted to document these updates for now.

**Comment by ian-r-rose** [comment]
Ooh, these new flags seem like they might be helpful! I think we are feeling enough pain in CI that an upgrade to 1.9 would be worth it.

**Comment by summer-mothwood** [comment]
Ian and I talked about this today and agreed on the following:
- these new flags seem like they might exactly solve our slimci issues
- this is a big enough problem (using unnecessary resources!) that we think it's worth it to prioritize upgrading our dbt version in order to test/use
    - 1.7 entered end-of-life on Nov 1st 2024 anyway
- Before we upgrade our dbt version, I'm going to take a look at documentation on the move from 1.7+ -> Versionless and call out any red flags for the team, then develop a schedule / communication plan for the upgrade.

Once we're ready to upgrade our dbt version, the general steps to do so is:
- Update the pyproject.toml
    - this should trigger a CI check 
- Dbt cloud environments (in this order) 
    - Development
    - CI
    - Production

Once in Versionless, we can then start working on setting the `state_modified_compare_more_unrendered_values` flag to true (will need to rebuild the state first, as mentioned in the documentation). More reading here: https://docs.getdbt.com/reference/global-configs/behavior-changes#source-definitions-for-state

**Comment by jkarpen** [comment]
This is blocked until dbt versionless change is implemented.

**Comment by summer-mothwood** [comment]
Great news! Upgrading to Versionless and turning on the new [state modified flag](https://docs.getdbt.com/reference/global-configs/behavior-changes#source-definitions-for-state) seems to have made slim CI work better, as we hoped it would. I ran a quick before-and-after test where I opened a PR with the same change on a downstream model before the new state modified behavior and after:

Before:
* CI build took 18m 45s
* https://california.getdbt.com/deploy/6/projects/10/runs/6736/
* logs show the behavior noted in this issue from the beginning: all incremental models that were upstream from the changed models (so shouldn't have been re-run in slim CI) but had environment-dependent variables making them 'look' changed b/n dev and prd were re-run


The CI build ran 23 incremental models, 25 table models, and 3 view models for this PR
![Image](https://github.com/user-attachments/assets/06c640b7-4f12-471a-a5b2-bb03425e4e06)



After:
* CI build took 13m 47s (~70% time decrease)
* https://california.getdbt.com/deploy/6/projects/10/runs/6763
* logs show the behavior we expect to see in CI -- only the changed models are run

And the CI build only ran 2 table models for this PR
![Image](https://github.com/user-attachments/assets/3bd26c52-f9a5-4aa6-83ce-3f4e69383a3d)


Closing this issue!
