### ISSUE TITLE
Training Session on Python Pipeline Development

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#363]
Requested by Zhenyu during Snowflake Architecture meeting:

How do we develop a python pipeline and use it as part of daily ETL tasks? For example: get the data from mart tables and push the data to ArcGIS service via their API.

**Comment by JamesSLogan** [comment]
@britt-allen could you review these slides? https://docs.google.com/presentation/d/1__SPVqRb3UWgk3wbrvh_1IRz9gkoUERfKDci_JijUYk/edit

**Comment by britt-allen** [comment]
I left some feedback on the slides @JamesSLogan
