### ISSUE TITLE
How to resolve errors in CI pipeline

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#364]
This will be an advanced training session for Caltrans on how to resolve errors in the CI pipeline. Will require developing new training materials.

**Comment by jkarpen** [comment]
Plan is for @tnrahim to begin work on these slides during sprint 2024-20, but aiming to hold the session during sprint 2024-21 or later.

**Comment by tnrahim** [comment]
Building Draft Presentation here -> https://drive.google.com/drive/folders/1IokXFeUfhUvPaVzD4VVwk4OTjilHunoD

**Comment by britt-allen** [comment]
@tnrahim [day 4 in our dbt Cloud training](https://docs.google.com/document/d/1K4z9VuHKco66z4Cp3n2xC67SNbRBSZe4uwXtJ7S0Cm8/edit#heading=h.ei47eqwnugu5) is where we do a brief CI/CD intro

**Comment by jkarpen** [comment]
@tnrahim please include discussion of how ODI uses GitHub actions for CI in these slides.

**Comment by ian-r-rose** [comment]
Closing as complete, thanks @tnrahim
