### ISSUE TITLE
Implement alerting to know when different pipelines may be down

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#376]
From Ian:
There are internal dashboards at Caltrans for monitoring the data relay server and identifying any incidents or downtime. It would also be good to implement some freshness checks on the data consumer side to ensure that the raw data uploaded looks the way we expect.

One relatively straightforward way of doing this would be to implement a “[source freshness](https://docs.getdbt.com/docs/deploy/source-freshness)” check in our dbt project, which ensures that the source tables always have data that are at least as recent as some target date (often a few days in the past). We would create one source freshness check for each table involved in the data relay effort. This task would not need any special permissions in Snowflake, and could be implemented by anyone using the TRANSFORMER_DEV role.

Another approach could be to monitor the [copy history](https://docs.snowflake.com/en/user-guide/data-load-monitor) of the target tables for the data relay server to ensure that there are as many file uploads as we expect on any given date. This would require access to the SNOWFLAKE database, which would mean a bit of administrative work to ensure that the transformer roles can make the queries they need.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
The first approach is chosen.

**Comment by jkarpen** [comment]
This is completed per @pingpingxiu-DOT-ca-gov
