### ISSUE TITLE
Speeds and G-factors

### ISSUE THREAD

**Issue by thehanggit** [cagov/caldata-mdsa-caltrans-pems#386]
The PeMS system has the ability to compute speed for sensors that don't report speed, like single loop detectors. If the sensors are reporting speed, like with radar detectors deployed head-on, or double loop detectors, then we can use those speed measurement directly. This is a configuration option that needs to be specified when the system is configured. When we need to compute speeds, we follow the algorithm outlined below.

Traditionally speed has been computed by using a g-factor in combination with the flow and occupancy. The g-factor is a value that represents the effective length of the vehicle. It is a combination of the average length of the vehicles in the traffic stream and the tuning of the loop detector itself. Typically, a constant value for the g-factor is used which leads to inaccurate speeds because the g-factor varies by lane, time-of-day, as well as the loop sensitivity. PeMS estimates a g-factor for each loop for every 5 minutes over an average week to provide accurate speed estimates. The algorithm has been tested and validated against ground truth data from double loop detectors and floating cars.

The algorithm that we have implemented in the PeMS system is adapted from the paper ["Statistical methods for estimating speed using single-loop detectors,"](https://pems.dot.ca.gov/Papers/vanzwet_gfactor.pdf) by van Zwet, Chen, Jia and Kwon.

The steps for the estimation of speed from that paper are as follows:

They start by making the assumption that the speed on the freeway at free-flow conditions is known and constant. A couple of notes:
Free-flow is defined by having the occupancy less than a certain threshold.
The free-flow speed is only a function of the type of freeway (meaning the total number of lanes) and the particular lane that the detector is in. For example, the free-flow speed in lane 2 of a 2-lane freeway is different from the free-flow speed in lane 2 of a 5-lane freeway.
We have double loops in the Bay Area. We used these to measure the actual free-flow speeds on different types of freeways and in different lanes. We have a table that gives the free-flow speed for each lane of each type of freeway. We apply that to the entire state.
Using this assumption then for each loop we can work backwards and compute the g-factor for a number of points during a number of days.
We then smooth this using a robust adaptive regression method to obtain a g-factor for each loop in the system over a typical week. All of the computation for g-factors is done offline.
This g-factor is then used to compute the initial estimate of speed for each loop in real-time.
This initial estimate is passed through an exponential filter with weights that vary as a function of the flow. When the flow at the loop is low the smoothing is quite severe. When the flow is high, there is little smoothing. This allows us to quickly adapt to periods of congestion as well as to have stable speeds when there is very little data (like in the middle of the night).
The resulting speed is what is actually used as our estimate of speed.

The table of speeds that we use in the first step above is given below:

![image](https://github.com/user-attachments/assets/9e210603-f91e-43be-9ef2-a0d3cdb1ad2f)

A couple of notes about the free-flow speeds:

Lane 1 is always the inside (or left) lane.
These were taken from the Bay Area in California, USA.
When localizing the PeMS system we can use different values for freeflow speed if supplied. If needed we convert these to metric.
For the HOV lanes we didn't have any ground truth data. Therefore we set the speeds to be 65MPH.
We didn't have ground truth data for 6 or 7 lanes freeways. Therefore we set the speeds to be equal to those from the 5-lane freeway.

**Comment by thehanggit** [comment]
The sensor summary report is accessible at: https://pems.dot.ca.gov/dnode=State&content=detector_health&tab=dh_summary_tracking

The total number of single loop detectors out of all detectors is 3573/30705, representing 11.64%. Of these, only 743 out of 23732 are deployed in GP and HOV lanes.

**Further analysis of the dataset revealed that speed data from dual loop detectors are also calculated, not directly measured**

**Comment by thehanggit** [comment]
![image](https://github.com/user-attachments/assets/9a762c0e-9fa5-408c-9728-b1baf9869b1d)

**Comment by thehanggit** [comment]
![image](https://github.com/user-attachments/assets/28d54642-adcd-47b7-aea4-172f247dd878)

**Comment by thehanggit** [comment]
![image](https://github.com/user-attachments/assets/8d5e9dcf-285f-4881-a4ce-649f398df5bc)

**Comment by thehanggit** [comment]
PeMS G-factor calculation for a designated station through investigation:

- Denote the 60-th percentile of the observed occupancies **$\alpha_{0.6}$**.
- Compute the unbiased estimate of g-factor **$g(t)$** as **$\frac{1}{N_{sample}} \sum_{\rho(t) <\alpha_{0.6}} \frac{v_f \rho(t)}{N(t)}$**, where **$\rho(t)$** represents the occupancy at time, **$v_f$** represents the free flow speed of a specific lane, **$N_{sample}$** represents the number of samples meeting the occupancy criteria, and **$N(t)$** represents the volume during the time step. 
- Additionally, if there is no data, we will choose a pre-defined constant **$\bar{g}$**. Currently, the time window for g-factor computation and refresh is assumed 1 hour as attached
![image](https://github.com/user-attachments/assets/9115d577-0267-4150-9e1a-6dc2f41cde04)
- Calculate a preliminary estimator of speed **$\hat{v}(t) = \frac{N(t)g(t)}{\rho(t)}$**.
- Pass through an exponential filter to obtain smoothing speed **$\tilde v(t) = p(t)\hat{v}(t) + (1-p(t))\tilde v(t-1)$**.
- Complete.

**Comment by jkarpen** [comment]
This issue is for developing the algorithm only, there will be a separate issue for QA/QC of this and other new algorithms.
