### ISSUE TITLE
Grant Yanlin Qi access to infrastructure

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#388]
Yanlin needs access to GitHub so she can be assigned issues. 
GitHub username: YanlinQi-BIA
Caltrans email: Yanlin.Qi@dot.ca.gov

- [x] GitHub
- [x] Snowflake
- [x] dbt Cloud

**Comment by jkarpen** [comment]
@kengodleskidot @pingpingxiu-DOT-ca-gov Just wanted to confirm, I'm assuming she will need access to Snowflake as well? Will she be using dbt?

**Comment by kengodleskidot** [comment]
> @kengodleskidot @pingpingxiu-DOT-ca-gov Just wanted to confirm, I'm assuming she will need access to Snowflake as well? Will she be using dbt?

Yes please @jkarpen and thank you!

**Comment by jkarpen** [comment]
@britt-allen can you submit the ticket for Yanlin's access for GitHub and give her access to Snowflake? Possibly also dbt Cloud, waiting for confirmation on that.

**Comment by britt-allen** [comment]
Helpdesk ticket for GitHub access: https://airtable.com/app1Jm2SLJEU3ljBr/pagUUMkYMw6S6Gg5n?detail=eyJwYWdlSWQiOiJwYWdRM3BIZWQ4eXdYd2VNRiIsInJvd0lkIjoicmVjbkZQa3gwS1Q4eXN5cmYiLCJzaG93Q29tbWVudHMiOnRydWUsInF1ZXJ5T3JpZ2luSGludCI6bnVsbH0&BPJfY=sfsqQddx4Rwz7PzCR

**Comment by britt-allen** [comment]
other help desk ticket: https://airtable.com/app1Jm2SLJEU3ljBr/pagUUMkYMw6S6Gg5n?detail=eyJwYWdlSWQiOiJwYWdRM3BIZWQ4eXdYd2VNRiIsInJvd0lkIjoicmVjZk1ieXY1UzhCQ2ZIQ0giLCJzaG93Q29tbWVudHMiOmZhbHNlLCJxdWVyeU9yaWdpbkhpbnQiOm51bGx9&BPJfY=sfsqQddx4Rwz7PzCR

**Comment by britt-allen** [comment]
I need access to [this](https://github.com/orgs/cagov/teams/caldata-mdsa-caltrans-pems) to add new team members. Ian set it up so that only he can which is a problem since he is OOO.

**Comment by britt-allen** [comment]
This is currently blocked by IT and the fact that Caltrans' end date has passed for access cc: @jkarpen

**Comment by YanlinQi-BIA** [comment]
I have access tp review this repo, but could not submit issues.

**Comment by britt-allen** [comment]
That's because you have to accept the invite I emailed you about at 10:20
am. Can you check your email please and follow the instructions there?
