### ISSUE TITLE
Schedule and prepare for executive kickoff with Caltrans

### ISSUE THREAD

**Issue by jasonlally** [cagov/caldata-mdsa-caltrans-pems#39]
- [ ] Identify the people to include in the meeting
- [ ] Schedule meeting (we can ask Sheryl to help us)
- [ ] Create presentation

**Comment by jasonlally** [comment]
@jkarpen - we can check in on this during mid-sprint. I think I can get this started and work with Sheryl in admin for scheduling support. May want your help on drafting a deck based on prior ones.

Target would be late Feb I think

**Comment by ian-r-rose** [comment]
This never happened. We should have a discussion in our project oversight meeting to set up a more deliberate strategy for communicating to execs
