### ISSUE TITLE
Kibana PEMS Bottleneck Dashboard

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#399]
https://planner.cloud.microsoft/caltrans.onmicrosoft.com/Home/Task/AcuVg6G5vESlizYVFmqoUIIAHNVT?Type=TaskLink&Channel=Link&CreatedTime=638627269843870000

This issue is to create and demo the PEMS Bottleneck dashboard.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
@ZhenyuZhu-Caltrans @mmmiah @thehanggit

**Comment by jkarpen** [comment]
Pingping created and demoed the dashboard to the Caltrans team already so this issue is being closed.
