### ISSUE TITLE
Investigate performance regression

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#414]
Since about two days ago, our nightly jobs went from taking about 30 minutes to about two hours. It seems that this is mostly being driven by [`int_clearinghouse__detector_agg_five_minutes_with_missing_rows`](https://california.getdbt.com/deploy/6/projects/10/runs/5449?tabId=model-timing), and the most likely culprit is something to do with #408 

@kengodleskidot and @mmmiah, do you know what might be going on there?

**Comment by ian-r-rose** [comment]
Ah, great, thanks @JamesSLogan

**Comment by kengodleskidot** [comment]
When updating this model in #408, I believe the most time-consuming step is in the `spine` CTE where we join the 5-minute time intervals with the detector. If there is a way to limit this join to the same timeframe as the `detector_agg` CTE that would drastically reduce the time to process this model.
