### ISSUE TITLE
Apply updates to Snowflake terraform configuration  - CalTrans DEV Environment

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#422]
We're making some updates to our terraform configuration for Snowflake to avoid some recent deprecations in https://github.com/cagov/data-infrastructure/pull/172

Once that is done, we should apply those updates here. It should be close to a no-op, but will help keep things up-to-date

- [x] Update snowflake terraform provider to from 0.88 to 0.92 on Dev - Step 1
- [ ] Update snowflake terraform provider to from 0.92 to 0.97 on Dev - Step 2

**Comment by ram-kishore-odi** [comment]
No additional actions may be needed after the 0.97 prd upgrade for resolving ticket based on current analysis. Need to confirm with Ian

**Comment by ram-kishore-odi** [comment]
This will also include Terraform AWS provider update to 5.75
During the standup it has also been decided to split this work into two tickets - one for dev and another for production environments.

**Comment by ian-r-rose** [comment]
I believe the nightly build issues are resolved, apply away!

**Comment by ram-kishore-odi** [comment]
Great ! I will apply the changes to development first before proceeding any further production related config updates

**Comment by ram-kishore-odi** [comment]
I am encountering a strange error that did not show up earlier. The plan log file also did not give any indications as far as I can tell.
Here is the plan log file - [cal-trans-final-0.97-plan-dev.txt](https://github.com/user-attachments/files/18031012/cal-trans-final-0.97-plan-dev.txt)


module.elt.snowflake_grant_account_role.reader_to_github_ci: Modifications complete after 0s [id="READER_DEV"|USER|"GITHUB_ACTIONS_SVC_USER_DEV"]
╷
│ Error: unexpected number of parts 1 in identifier PEMS_RAW_DEV, expected 3 in a form of "<database_name>.<schema_name>.<schema_object_name>"
│ 
│   with module.snowflake_clearinghouse.snowflake_grant_privileges_to_account_role.pems_raw,
│   on ../../modules/snowflake-clearinghouse/main.tf line 69, in resource "snowflake_grant_privileges_to_account_role" "pems_raw":
│   69: resource "snowflake_grant_privileges_to_account_role" "pems_raw" {
│ 
╵
╷
│ Error: unexpected number of parts 1 in identifier PEMS_MARTS_DEV, expected 3 in a form of "<database_name>.<schema_name>.<schema_object_name>"
│ 
│   with module.snowflake_clearinghouse.snowflake_grant_privileges_to_account_role.pems_marts,
│   on ../../modules/snowflake-clearinghouse/main.tf line 92, in resource "snowflake_grant_privileges_to_account_role" "pems_marts":
│   92: resource "snowflake_grant_privileges_to_account_role" "pems_marts" {
│ 
╵
╷
│ Error: warehouse suspension failed, err: giving up after 3 attempts, original errors: %!w(<nil>)
│ 
│   with module.elt.module.transforming["XS"].snowflake_warehouse.this,
│   on .terraform/modules/elt/terraform/snowflake/modules/warehouse/main.tf line 38, in resource "snowflake_warehouse" "this":
│   38: resource "snowflake_warehouse" "this" {

**Comment by ian-r-rose** [comment]
I'll bet it's because a CI job was running and using the warehouses when you tried to recreate them

**Comment by ian-r-rose** [comment]
At least, for the last one. For the first two, I'm not sure, but the error message at least looks helpful

**Comment by ram-kishore-odi** [comment]
Thank you for your feedback ! Every time I run a plan, I am getting a different output so I am just looking at the plan logs

**First example**

Please see the examples below - Plan: 20 to add, 3 to change, 0 to destroy.

Changes to Outputs:
  ~ notification_channel = "arn:aws:sqs:us-west-2:946158320428:sf-snowpipe-AIDA5YS3OHMWCVTR5XHEE-YZjsweK3loK4rXlOJBWF_g" -> (known after apply)
╷
│ Warning: Failed to describe stage. Marking the resource as removed.
│ 
│   with module.snowflake_clearinghouse.snowflake_stage.pems_raw,
│   on ../../modules/snowflake-clearinghouse/main.tf line 58, in resource "snowflake_stage" "pems_raw":
│   58: resource "snowflake_stage" "pems_raw" {
│ 
│ Stage: "RAW_DEV"."CLEARINGHOUSE"."PEMS_RAW_DEV", Err: [errors.go:22] object does not exist or not authorized

**Second example**
    }

  # module.elt.module.transforming["XS"].snowflake_warehouse.this will be updated in-place
  ~ resource "snowflake_warehouse" "this" {
        id                                  = "TRANSFORMING_XS_DEV"
      ~ max_concurrency_level               = 8 -> (known after apply)
        name                                = "TRANSFORMING_XS_DEV"
      ~ statement_queued_timeout_in_seconds = 0 -> (known after apply)
      ~ statement_timeout_in_seconds        = 172800 -> (known after apply)
        # (14 unchanged attributes hidden)
    }

Plan: 13 to add, 3 to change, 0 to destroy.
╷
│ Error: open snowflake connection: 390195 (08004): The provided ID Token is invalid.
│ 
│   with provider["registry.terraform.io/snowflake-labs/snowflake"].accountadmin,
│   on main.tf line 60, in provider "snowflake":
│   60: provider "snowflake" {

**Comment by ram-kishore-odi** [comment]
CalTrans dev. environment changes to upgrade v0.97 are complete. Please see the log below.


***************************************************************************************************
  Enter a value: yes

module.snowflake_clearinghouse.snowflake_grant_privileges_to_account_role.pems_raw: Creating...
module.snowflake_clearinghouse.snowflake_grant_privileges_to_account_role.pems_raw: Creation complete after 1s [id="LOADER_DEV"|false|false|USAGE|OnSchemaObject|OnObject|STAGE|"RAW_DEV"."CLEARINGHOUSE"."PEMS_RAW_DEV"]
module.snowflake_clearinghouse.snowflake_grant_privileges_to_account_role.pems_marts: Creating...
module.snowflake_clearinghouse.snowflake_grant_privileges_to_account_role.pems_marts: Creation complete after 0s [id="TRANSFORMER_DEV"|false|false|USAGE|OnSchemaObject|OnObject|STAGE|"ANALYTICS_DEV"."PUBLIC"."PEMS_MARTS_DEV"]

**Apply complete! Resources: 2 added, 0 changed, 0 destroyed.**
***************************************************************************************************
odule.snowflake_clearinghouse.snowflake_pipe.station_status_pipe: Refreshing state... [id=RAW_DEV|CLEARINGHOUSE|STATION_STATUS]
module.snowflake_clearinghouse.snowflake_pipe.station_raw_pipe: Refreshing state... [id=RAW_DEV|CLEARINGHOUSE|STATION_RAW]
module.snowflake_clearinghouse.snowflake_grant_privileges_to_account_role.pems_marts: Refreshing state... [id="TRANSFORMER_DEV"|false|false|USAGE|OnSchemaObject|OnObject|STAGE|"ANALYTICS_DEV"."PUBLIC"."PEMS_MARTS_DEV"]

**No changes. Your infrastructure matches the configuration.**

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
********************************************************************************************************

**Comment by ian-r-rose** [comment]
Thanks @ram-kishore-odi !
