### ISSUE TITLE
Resolve build failure

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#424]
Our nightly job [failed](https://california.getdbt.com/deploy/6/projects/10/runs/5668/) last night due to some duplicate values in the `int_performance__detector_metrics_agg_five_minutes` model. In the past, this has meant that somehow there are some detector_id/timestamp combinations that are repeated (either in the source data or due to a bug in some upstream model).

**Comment by JamesSLogan** [comment]
#### Resolution status

This should be resolved now. No code changes ended up being needed (@summer-mothwood fyi). Nightly build [retry](https://california.getdbt.com/deploy/6/projects/10/runs/5685) has passed. 

#### Investigation notes

Recently (today?), 2 detectors were moved (see metadata query below) from lane 1 to lane 2 within their respective stations. This resulted in the detectors showing up more than once across some combinations of `station_id`/`sample_timestamp` in `int_imputation__detector_agg_five_minutes`, which is immediately upstream from the model presenting the error. A full refresh of this model cleared up this issue.

I'm not 100% clear on the exact specifics of the error. My best guess is something like this, roughly:
- 2024-10-12: incremental row set for detector A (lane 1)  includes these days: 9, 10, 11
-  2024-10-13: incremental row set for detector A (lane 1)  includes these days: 10, 11, 12
-  2024-10-14: incremental row set for detector A (lane 1)  includes these days: 11, **12, 13**
-  2024-10-15: incremental row set for detector A (lane 2!) includes these days: **12, 13**, 14
   - ^At this point detector A has multiple entries per day for the 12th and 13th

#### Can this happen again?

Yes, I think so. Updating models to merge in new records using `detector_id` should prevent this. We will discuss this with the Caltrans team and open an issue as necessary.


#### Metadata query
```sql
select detector_id, station_id, lane, _valid_from, _valid_to
from transform_prd.vds.int_vds__detector_config
where detector_id in ('30900617', '30900717') and _valid_from > '2024-10-01'
order by detector_id, station_id, lane, _valid_from
;
```
