### ISSUE TITLE
A QC Dashboard shows the number of detectors balance between different models over time

### ISSUE THREAD

**Issue by mmmiah** [cagov/caldata-mdsa-caltrans-pems#425]
Create a dynamic dashboard that will show number of detectors count over two weeks dynamic time period from different models. Ken already created that datasets in mart level. We need to make the connection between that mart table and kibana usinsg logstash to push the data for visualization and then schedule the data update everyday early night around 3.30 am to update the data in daily basis.  This visualization will compare the number of detectors for the below models-

a. HOV and ML total number of daily detectors
b. HOV and ML detectors daily count from five minutes performance model
c. HOV and ML detectors daily count from Imputed model
d. HOV and ML detectors daily count from cleanhouse 
e. Number of Bad, Good and Total Detectors

**Comment by kengodleskidot** [comment]
Thanks for this @mmmiah and I have created a new issue (#426) to document/fix the detector_status data issue we are seeing since 10/8/24.

**Comment by jkarpen** [comment]
Per @mmmiah this work is completed so we can close this issue.
