### ISSUE TITLE
Detector Status Not Updating Properly

### ISSUE THREAD

**Issue by kengodleskidot** [cagov/caldata-mdsa-caltrans-pems#426]
I reviewed @mmmiah screenshot in #425 and checked the detector_status model data in Production and it appears the data in the Production detector_status model is not updating properly. Below and attached are the results when I build the model in Dev which look correct. We should see approximately 25k Good detectors on any given date but in Production the statuses are all bad since 10/8/24. 
[PRD-Diagnostic.csv](https://github.com/user-attachments/files/17385070/PRD-Diagnostic.csv)
![image](https://github.com/user-attachments/assets/b716235d-53bb-4008-8293-6e05d3f51838)

**Comment by mmmiah** [comment]
I am just guessing that dev and production is not synchronized properly for night job!

**Comment by JamesSLogan** [comment]
Taking a look!
