### ISSUE TITLE
 Create a QC dashboard that will show daily number of detectors by its health status

### ISSUE THREAD

**Issue by mmmiah** [cagov/caldata-mdsa-caltrans-pems#428]
We have already created mart level data  named 'DIAGNOSTICS__DETECTOR_DAILY_BY_STATION' that contains the details breakdown count of detectors health. Use two weeks dynamic detector status to develop dashboard that will track the details health status breakdown and ensure data quality over time. This model has county code, make sure county full name reflects before using the data in dashboard p[reparation.
 Following visualization can be developed-
a.  two weeks Good and bad detectors time series daily count
b. Details Breakdown of daily detectors count by health status such as constant count, card off, down, high value issues, insufficient data, and intermittent count
c. Health status Breakdown by District, County, Route, and station type

**Comment by jkarpen** [comment]
This is dependent on the county name PR #443  to be reviewed/completed before this can start.

**Comment by mmmiah** [comment]
A draft dashboard of detector daily health has been established, here is the link
https://svgcmdl02:5601/app/dashboards#/view/e5133f00-9afa-11ef-8f47-a5289c4fae81?_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-15d%2Cto%3Anow))
