### ISSUE TITLE
AADT Pattern Monitoring by corridor over multiple years

### ISSUE THREAD

**Issue by mmmiah** [cagov/caldata-mdsa-caltrans-pems#431]
As part of the QC, we will utilize our mart model named 'PERFORMANCE.PERFORMANCE__STATION_AADT_K_VALUE' that have reported historical AADT and K -factors for each station. We can easily use this data table to grab last 2-3 years AADT data and show some visualization by corridor or freeway/route level. Over the consecutive time period AADT should not drop too much by the corridor level. If there is unusual drop of AADT noticed, we need to investigate our data processing. This dashboard will be dynamic using last 2-3 years data and update the map yearly basis using scheduler of corn job in logstash and visualization will be done in kibana through elastic search data absorption.

**Comment by mmmiah** [comment]
Here is the aadt kibana dashboard draft for the review: Please have your review and let me know your feedback. Thanks!
https://svgcmdl02:5601/app/dashboards#/view/66a3c070-90b6-11ef-af1a-8553ba48f88d?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2y,to:now))&_a=(description:'',filters:!(),fullScreenMode:!t,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:station_aadt_k-value_performance_dashboard,viewMode:view)

**Comment by thehanggit** [comment]
Thank you Mintu for your great efforts! The AADT by freeway is bit unclear and the filter window is somehow blocked by the map. Can you please adjust them?

**Comment by thehanggit** [comment]
> Thank you Mintu for your great efforts! The AADT by freeway is bit unclear and the filter window is somehow blocked by the map. Can you please adjust them?

By "unclear" I mean it's hard to differentiate different AADTs

**Comment by mmmiah** [comment]
@thehanggit ,Thanks for quick review. Do you see different than me
![image](https://github.com/user-attachments/assets/4717bbeb-d08a-4a0c-a51c-5bd7289fa547)
 We calculated eight different AADT, those are looks have minor difference from each others due to their calculation criteria. As long as those are close to each others our calculated AADT looks good!

**Comment by thehanggit** [comment]
Yes, it's the same dashboard. Looks good!

**Comment by jkarpen** [comment]
Per @mmmiah this dashboard is completed and has received feedback so closing this issue.
