### ISSUE TITLE
Double-down on ELK (Elasticsearch, Logstash, Kibana) feasibility 

### ISSUE THREAD

**Issue by pingpingxiu-DOT-ca-gov** [cagov/caldata-mdsa-caltrans-pems#435]
Compiler is waiting for their PeMS Website Architecture Proposal feedback from Caltrans. (**Time Sensitive**)
In their architecture, they proposed ELK stack. 

There are open questions in terms of finalizing Architecture Design: 

- [ ] Should new PeMS use ELK's Workspace Search, or build search from API? 
- [ ] They say ElasticCloud can auto-scale so they wouldn't investigate the self hosting. I think investigating self-hosting is important. 
- [ ] Map Tile Service, do they have to rely on third-party? I know how to build by self. 
- [ ] ...

**Comment by jkarpen** [comment]
@pingpingxiu-DOT-ca-gov aiming to complete this by 10/28 deadline requested by Compiler.

**Comment by peacexerox** [comment]
All comments on the docs

https://docs.google.com/document/d/1yX9R6fQekiFCe4y0nndDg0zSx6aouis3TGgbc0YOF5g/edit?tab=t.0

Summary, the ElasticCloud (focusing on version 7.9.2) is a feasible solution to start. 

Closing this issue
@ZhenyuZhu-Caltrans

**Comment by pingpingxiu-DOT-ca-gov** [comment]
All comments on the docs

https://docs.google.com/document/d/1yX9R6fQekiFCe4y0nndDg0zSx6aouis3TGgbc0YOF5g/edit?tab=t.0

Summary, the ElasticCloud (focusing on version 7.9.2) is a feasible solution to start.

Closing this issue
@ZhenyuZhu-Caltrans
