### ISSUE TITLE
Create a bottleneck performance dashboard by stations

### ISSUE THREAD

**Issue by thehanggit** [cagov/caldata-mdsa-caltrans-pems#442]
Create a bottleneck performance dashboard using daily bottleneck delay metrics aggregation table with Kibana.

**Comment by thehanggit** [comment]
https://svgcmdl02:5601/app/dashboards#/view/d322a770-9692-11ef-8f47-a5289c4fae81?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15d,to:now))&_a=(description:'sample%20dashboard%20to%20demo%20filter,%20map,%20chart%20and%20table,%20by%20Zhenyu',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:dev_station_bottleneck_performance,viewMode:view)

**Comment by jkarpen** [comment]
Closing as this dashboard is completed. @thehanggit will create a separate issue for resolving data quality issues that were found.
