### ISSUE TITLE
Updating user settings in Snowflake

### ISSUE THREAD

**Issue by ram-kishore-odi** [cagov/caldata-mdsa-caltrans-pems#446]
Updated the user settings for the following users in Snowflake. These users were incorrectly setup initially and hence corrective action is needed

Arman (who recently requested access to CalTrans)
Summer & Ram (who were recently added to Snowflake)

The action required is to unset the password and add a login_name parameter with email as the value for all these users. This will ensure that users can only login through OKTA and will disable using username & password login mechanism.

**Comment by ram-kishore-odi** [comment]
The user settings have been updated and I have confirmed that all the users are able to login to Snowflake successfully using OKTA after the updates.
One of the users faced issues, probably an intermittent issues, which were later resolved by repeating the updates. Hence this issue can be closed.

**Comment by ian-r-rose** [comment]
Cool, thanks for the update
