### ISSUE TITLE
Apply updates to Snowflake terraform configuration - CalTrans - PRD Environment

### ISSUE THREAD

**Issue by ram-kishore-odi** [cagov/caldata-mdsa-caltrans-pems#475]
Snow terraform provider has been updated to 0.97. We should apply those updates here for CalTrans production environment. This will be done after the dev. environment is complete.

**Comment by ram-kishore-odi** [comment]
Production change are in progress now -

**Comment by ian-r-rose** [comment]
Can we merge #489 first?

**Comment by ram-kishore-odi** [comment]
Production config changes are in progress now. Terraform apply will happen later.

**Comment by ram-kishore-odi** [comment]
I am sorry I did not get to see to your comment earlier. Can you please let me know if I can merge after adding the updated lock files and other production config changes to this PR ( and after the review) ? I am open to any changes to this approach.

**Comment by ian-r-rose** [comment]
Yes, go ahead!

Ian Rose (he/him)
Principal Data Engineer, Data Services | CA Office of Data and Innovation
(916) 931-8386 | ***@***.***
Follow us: web <https://innovation.ca.gov/> | blog
<https://innovation.ca.gov/blog/> | twitter
<https://twitter.com/californiaodi>

**Comment by ian-r-rose** [comment]
Looks great, thanks @ram-kishore-odi!

**Comment by ram-kishore-odi** [comment]
hi @ian-r-rose, Please see the PRD version 0.92 log attached - [jsr-prd-tf-v0.92-upgrade.txt](https://github.com/user-attachments/files/18104291/jsr-prd-tf-v0.92-upgrade.txt)

- Code referring to the right commit - github.com/cagov/data-infrastructure.git//terraform/snowflake/modules/elt?ref=9e032a9

- Also **please note**, I have **not yet** removed the following in order not to disturb state file.

terraform state rm 'module.snowflake_clearinghouse.snowflake_stage_grant.pems_marts'
terraform state rm 'module.snowflake_clearinghouse.snowflake_stage_grant.pems_raw'
terraform state rm 'module.snowflake_clearinghouse.snowflake_integration_grant.pems_storage_integration_to_sysadmin'

- Reosurces resource "snowflake_grant_privileges_to_account_role" "pems_raw" & resource "snowflake_grant_privileges_to_account_role" "pems_marts" are referring to the updated code unlike in dev. But no errors in the plan / validate

- The main thing that is bothering me is the output - Plan: 118 to add, 0 to change, 234 to destroy. 
- The resources getting destroyed are having a message similar to this -    module.elt.module.transforming["XS"].snowflake_warehouse_grant.this["USAGE"] will be destroyed
 (_because snowflake_warehouse_grant.this is not in configuration_)

- I have not made any changes different from dev. Can you please let me know if you see any red flags ?

I am continuing to review to determine any differences from dev.

**Comment by ian-r-rose** [comment]
>  The main thing that is bothering me is the output - Plan: 118 to add, 0 to change, 234 to destroy.

This is roughly what we expect: the grant refactor resulted in many fewer grant resources (a nice simplification!).

> The resources getting destroyed are having a message similar to this - module.elt.module.transforming["XS"].snowflake_warehouse_grant.this["USAGE"] will be destroyed
(because snowflake_warehouse_grant.this is not in configuration)

We also expect this: all of the specific `grant` resources are intended to be replaced with the more general `snowflake_grant_privileges_to_account_role`.

I think this is looking correct to me, no red flags right now!

**Comment by ram-kishore-odi** [comment]
Thank you so much for your feedback @ian-r-rose !! I plan to apply these late in the evening today (assuming that the notification will go out to the CalTran team shortly).

**Comment by ram-kishore-odi** [comment]
Hi @ian-r-rose, Please see the latest v0.97 upgrade plan for Caltrans. This is after removing all the 24 snowflake_role resources and reimporting them. I did the same for the 2 CalTrans schema resources - [jsr-terraform-plan-after-all-manual-steps.txt](https://github.com/user-attachments/files/18157997/jsr-terraform-plan-after-all-manual-steps.txt)

Even after removing the 2 schemas from state and importing them back into state, I still see the following messages. Also the plan says they must be replaced - Can you please review the plan share your. feedback ?

Do you want me to remove them from state - apply the changes and then import them back into state ? 

***********************************
(infra) ram.kishore@180 prd % terraform plan -no-color -parallelism=1 > jsr-terraform-plan-after-all-manual-steps.txt          

Error: Instance cannot be destroyed

  on ../../modules/snowflake-clearinghouse/main.tf line 22:
  22: resource "snowflake_schema" "pems_clearinghouse" {

Resource module.snowflake_clearinghouse.snowflake_schema.pems_clearinghouse has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with
the plan, either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target option.

Error: Instance cannot be destroyed

  on ../../modules/snowflake-clearinghouse/main.tf line 34:
  34: resource "snowflake_schema" "pems_db96" {

Resource module.snowflake_clearinghouse.snowflake_schema.pems_db96 has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan,
either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target option.

***********************************

**Comment by ram-kishore-odi** [comment]
The version 0.97 upgrade has been completed in the production environment.
