### ISSUE TITLE
Investigate+fix mart unloading failure

### ISSUE THREAD

**Issue by JamesSLogan** [cagov/caldata-mdsa-caltrans-pems#478]
During [a CI run](https://california.getdbt.com/deploy/6/projects/10/runs/6275), one of our marts failed to unload to s3 due to a large file size:

```
Database Error in model imputation__detector_summary (models/marts/imputation/imputation__detector_summary.sql)
  100083 (22000): Max file size (536870912) exceeded for unload single file mode.
    We recommend that you increase the max file size parameter, or disable single-file mode 
    in the unload command and combine the unloaded files into a single file after you download them.
```

It's not clear why this appears to only have happened once, but this should be investigated and fixed so that it doesn't eventually block CI/CD.

**Comment by jkarpen** [comment]
Putting this in the backlog as it has not happened since and may not happen again.

**Comment by jkarpen** [comment]
Closing as no longer needed, the problem has not happened again.
