### ISSUE TITLE
 Resolve duplicate geolocation of the station.

### ISSUE THREAD

**Issue by mmmiah** [cagov/caldata-mdsa-caltrans-pems#479]
We have created GEO__CURRENT_DETECTORS model in the mart to have geo-location for each station.  However, we found that there is duplicate latitude and longitude for same stations that impacts our other model uniqueness.  The current model repeats the detectors for each station which repeated the lat and long detector number times and cause the duplicate rows in upstream data processing. We need to consider unique station and its lat and long in such cases

**Comment by ian-r-rose** [comment]
What is the root cause of the duplicates? Is the issue that some stations are decommissioned, but not marked as such? I suggest figuring out what is causing the duplicate lat/lon values in the upstream data, rather than deduplicating in the mart itself.

**Comment by ian-r-rose** [comment]
The current detectors model already takes into account the `_valid_to` field: https://github.com/cagov/caldata-mdsa-caltrans-pems/blob/1aea68581620098be3ecf0185a594c101dd0f71b/transform/models/marts/geo/geo__current_detectors.sql#L10

This is why I asked if there might be some stations that are decommissioned in reality, but have not had their metadata updated

**Comment by mmmiah** [comment]
Here is list of stations that have pairs of lat and long in geo data
[station_duplicate.csv](https://github.com/user-attachments/files/17759166/station_duplicate.csv)


![image](https://github.com/user-attachments/assets/7c04eed5-23af-48cc-9e6c-e68f5b5b42f9)

**Comment by mmmiah** [comment]
@ian-r-rose , it seems that same station has different absolute post mile that generate different co-ordinate as ken mentioned that system use absolute post mile to generate the  lat and long that is causing issues for 38 stations out of 19,663 stations. As all the current detector geo location was already identified considering valid to. I think that we need to put one more filter to have unique lat and long for each station based on actual physical location of station. Any thoughts?

**Comment by ian-r-rose** [comment]
@mmmiah what table is that screenshot from? I think you *do not* want to filter for unique latitude/longitude in `geo__current_stations`, but instead should figure out where the duplicates are coming in upstream. That is to say, dealing with data quality issues in the marts is not a great solution when they could be dealt with at the staging or intermediate layers.

**Comment by mmmiah** [comment]
This duplicate is actually coming from stg_db96__detector_config_log/stg_db96__detector_config which indicates that it is the raw db96 problem. However, I found that we do not have any duplicate in int_vds__station_config which is related to stg_db96__station_config_log/stg_db96__station_config. 

The solution is to make station_current_geo available in mart based on int_vds__station_config will solve our issues. At the same time we need to discourage to use detector level geo when we need station lat and long.

All of my QC check is here: https://app.snowflake.com/vsb79059/dse_caltrans_pems/w2UYyYstWIkw#query

**Comment by ian-r-rose** [comment]
This issue of duplicate stations is also something that @summer-mothwood might be interested in as part of the work in https://github.com/cagov/data-infrastructure/issues/340

**Comment by JamesSLogan** [comment]
I think the issue is the assumption that sets of (`station_id`, `lat`, `long`) would be unique across _detectors_. Detector metadata times aren't identical and can capture station metadata at different times. Could we create a `geo__current_stations` model and use that in the two marts with duplicates? 

![image](https://github.com/user-attachments/assets/328acf67-e7ec-4556-897c-62e2e0fd1a37)

**Comment by mmmiah** [comment]
I will make geo__current_stations model using int_vds__station_config, this will help us to update upstream model while Summer can investigate stg_db96__detector_config for the issue

**Comment by mmmiah** [comment]
geo__current_stations model was created to solve this issues in downstream models. I am closing this issue for now, new issue can be created to solve multiple geo-location for a same station in detector file!
