### ISSUE TITLE
Dbt Cloud Log In Issue

### ISSUE THREAD

**Issue by thehanggit** [cagov/caldata-mdsa-caltrans-pems#488]
Ken and I have been unable to log into dbt could since last week using this [URL](https://california.getdbt.com/). It seems that some other Caltrans team members are also experiencing the same issue, although not everyone is affected (Mintu is able to log in).

Could you please look into this and let us know if there are any updates or solutions?

Thanks!

**Comment by ram-kishore-odi** [comment]
Hello Everyone,

Here is the latest update from DBT. They have identified the issue and are
working on it.

Thank you,
Ram Kishore

*****************************************

*Taylor* (dbt Labs Support)

Nov 27, 2024, 17:26 EST
Hi Ram,

Quick follow up - we have identified the problem and are working on a fix!

Taylor Erwin
Solutions Engineer, US
dbt Labs

****************************************

**Comment by thehanggit** [comment]
@ram-kishore-odi Thank you Ram for the quick response!

**Comment by ian-r-rose** [comment]
Hi @thehanggit can you check if you are able to log in now?
