### ISSUE TITLE
Provide feedback on draft milestone plan

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#6]
Draft CalTrans milestones are located here: https://coda.io/d/Data-Services-Engineering_dY5Oul8-jdi/Sprint-Plan_sudyr#CalTrans-Milestone-Plan_tuP1M/r78

Please review and provide  feedback by doing the following: 
1. If you think there are important milestones that should be included in the list, there is a section at the bottom of the page where you can write those in. We aimed to include milestones that:

- Are high level enough to have multiple issues within them
- Or are important tasks that we want to make sure are called out in the schedule

2. If you have feedback or questions on the milestones in the list, add a comment to that row. This can be done by clicking on the Milestone cell for that row and choosing "Add Comment"

**Comment by britt-allen** [comment]
What the deadline for this?

**Comment by jkarpen** [comment]
@britt-allen Original due date we listed was 9/29 (today), but given the focus on training prep this week we will probably push that to next week. We'll talk about it in Sprint Planning today.

**Comment by ian-r-rose** [comment]
Thanks @jkarpen, the milestone plan looks good to me. I added one additional milestone based on our discovery meeting yesterday to also load historical PeMS data, as it seems that will have a different process from ongoing pipelines.

**Comment by AeriShan-ODI** [comment]
I couldn't think of anything to add. There will likely be some detail
around creating the dbt model(s) but we won't really know what those are
until we see the sample data.
Aeri

**Comment by britt-allen** [comment]
I added one thing to training based off a learning from CARB with Ian today.
