### ISSUE TITLE
Create data pipeline issues

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#66]
Please create and populate issues for the following tasks:

- [x] Identify access method for LCS and CHP datasets

Items we can provide development support on:
- [x] Develop python or Snowflake scripts for processing XML files into structured data for all districts
- [x] Develop python or Snowflake scripts for processing XML files into structure data for configuration files

Items we cannot provide development support on, guidance only:
- [x] Create data relay pipeline for D7 VDS data
- [x] Create data relay pipeline for the rest of the districts data
- [x] Create data relay pipeline for VDS configuration XML files
- [ ] ~~Create data relay pipeline for LCS data~~

**Comment by jkarpen** [comment]
@ian-r-rose if it would help speed things up for you I can create placeholders for each of these for you to fill in details on later. Just let me know.

**Comment by ian-r-rose** [comment]
Closing as complete
