### ISSUE TITLE
Identify priority or low-lift metrics to drive EDA

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#69]
The goal here is to review the metrics document provided by Caltrans [here](https://docs.google.com/spreadsheets/d/1cQhmad4XBPGw8uUCzRCurVTo1JuGULNI/edit#gid=607116071) and identify the highest priority or lowest lift metrics that we will use to begin EDA on. Ken from the Caltrans side might be the right person to pair with on this (we can confirm in 2/22 sprint call with Caltrans team). 

- [ ] Identify criteria for how we will prioritize the metrics
- [ ] Create metric prioritizations

**Comment by jkarpen** [comment]
@britt-allen  please add the details on the item that came up in office hours since that sounded like a good place to start.

**Comment by britt-allen** [comment]
This was done and captured here: https://github.com/cagov/caldata-mdsa-caltrans-pems/issues/126
