### ISSUE TITLE
Investigate broken data relay server

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#73]
I don't see any updates to the current data relay pipeline since sunday. Am I looking in the wrong, place, or is your Airflow down @pingpingxiu-DOT-ca-gov?

**Comment by ian-r-rose** [comment]
Is the Kafka server related to this project?

**Comment by ian-r-rose** [comment]
Why do we need Kafka for this? I was under the impression that we were doing some one-time loads of some tables with config parameters.

**Comment by pingpingxiu-DOT-ca-gov** [comment]
We need Kafka for a variety of data relaying tasks.

**Comment by jkarpen** [comment]
Closing this as we are no longer grabbing raw data.
