### ISSUE TITLE
PeMS detector health diagnostics: too few data samples

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#79]
Implement Test number 2 from the [PeMS User Guide](https://pems.dot.ca.gov/Papers/PeMS_Intro_User_Guide_v6.pdf):

<img width="671" alt="image" src="https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/5728311/5cad0f23-54ec-493c-9ec5-b561e865ee48">

**Data sources**: 30 second raw data, VDS metadata (controller, station, detector)

**Comment by britt-allen** [comment]
@ian-r-rose thinks this issue (and the whole project) could be a good use case for dbt incremental models. See docs [here](https://docs.getdbt.com/docs/build/incremental-models) and [here](https://docs.getdbt.com/best-practices/materializations/4-incremental-models)

**Comment by ian-r-rose** [comment]
I don't think this is done yet, we still need to get #96 through review and in `main`, no?

**Comment by britt-allen** [comment]
If I am understanding correctly, even though I built the relevant model for this issue you want to keep this issue open until Ken merges his PR? @ian-r-rose

**Comment by ian-r-rose** [comment]
Yes, I don't think issues are considered done until they are merged to `main`.

**Comment by britt-allen** [comment]
That makes sense to me, thank you for clarifying!
