### ISSUE TITLE
PeMS detector health diagnostics: occupancy is constant

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#83]
Implement Test number 6 from the [PeMS User Guide](https://pems.dot.ca.gov/Papers/PeMS_Intro_User_Guide_v6.pdf):

<img width="671" alt="image" src="https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/5728311/f170783c-e911-418c-a174-31b012c268e7">

**Data sources**: 30 second raw data

**Comment by britt-allen** [comment]
Blocked by imputation logic

**Comment by britt-allen** [comment]
We need to update this to see what the values would look like for 30-sec data, would also want to make sure in the 4 hour window if we have 60% or more samples being constant that would trigger this test
