### ISSUE TITLE
PeMS detector health diagnostics: Not enough data samples received

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#84]
Implement Test number 7 from the [PeMS User Guide](https://pems.dot.ca.gov/Papers/PeMS_Intro_User_Guide_v6.pdf):

<img width="671" alt="image" src="https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/5728311/fff28a0e-f5d0-499f-85ab-9d0b6c65b200">

**Data sources**: 30 second raw data, VDS metadata (controller, station, detector)

It's not super clear to me how this test is different from the second one (cf #79 ), @kengodleskidot do you have any ideas?

**Comment by britt-allen** [comment]
Blocked and related to #79

**Comment by ian-r-rose** [comment]
Why is this blocked? This seems like a fairly straightforward groupby/count.

**Comment by britt-allen** [comment]
@kengodleskidot can add more color here but he essentially said he needs to understand this test more and if/how it is different than test number 2 (#79). So maybe not necessarily blocked, but on hold for now.

**Comment by britt-allen** [comment]
Ken is thinking about changing the logic and result of this test.

**Comment by kengodleskidot** [comment]
On 3/29/24 at 11pm the district 12 traffic data feed went down and no raw data was being sent from the TMC to PeMS. The feed began working and sending raw data to PeMS on 4/3/24. During the time the district 12 traffic feed was down the detector health status for district 12 detectors followed the logic for this test. As a result, I have created a status in the detector_status model that states the district feed is down to clarify what I believe this status represents.

**Comment by britt-allen** [comment]
Can this issue be closed? @kengodleskidot

**Comment by pingpingxiu-DOT-ca-gov** [comment]
@pingpingxiu-DOT-ca-gov  TODO review
