### ISSUE TITLE
Parse second column of the station_status table in Clearinghouse

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#89]
The `CONTENT` column in `RAW_PRD.CLEARINGHOUSE.STATION_STATUS` needs to be further parsed out as it is not human readable. This will allow us to easily get information on station to detector mapping.

**Comment by ian-r-rose** [comment]
@britt-allen can you add a description and project metadata?

**Comment by britt-allen** [comment]
I will when I get time.
